api/urls.py
from django.urls import include, path, re_path

from api.views.carto import PoiView
from api.views.viewsets import OrganisateurViewSet, SiteN2KViewSet
from api.views.manif import ManifestationViewSet, ManifPublicViewSet, ManifEnvViewSet
from api.views.instruction import InstructionViewSet
from api.views.avis import AvisView
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


app_name = 'api'
router = routers.DefaultRouter()
router.register(r'Calendrier', ManifPublicViewSet, basename='Calendrier')
router.register(r'Organisateur', OrganisateurViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'Evenement', ManifestationViewSet, basename='Evenement')
router.register(r'Avis', AvisView, basename='Avis')
router.register(r'Evenement_environnement', ManifEnvViewSet, basename='Evenement_environnement')
router.register(r'SiteN2K', SiteN2KViewSet, basename='SiteN2K')
router.register(r'Pois', PoiView, basename='Pois')

schema_view = get_schema_view(
    openapi.Info(
        title="API de manifestationSportive.fr",
        default_version='v1',
        description="Permet l'utilisation de la plateforme à partir d'une autre application\n"
                    "Les urls affichées sont celles que vous pouvez accèder",
        contact=openapi.Contact(name="Openscop", url="https://www.openscop.fr/", email="contact@openscop.fr"),
        license=openapi.License(name="Creative Commons BY-NC-ND 4.0", url="https://creativecommons.org/licenses/by-nc-nd/4.0/")
    ),
    public=False,
    patterns=[path('api/', include(router.urls))],
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include(router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

configuration/urls.py
from forum.urls import urlpatterns as machina_urls

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest, HttpResponseForbidden

from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from core.util.dynamic_static import staticfiles_dynamicurlpatterns
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview, login,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView,
                             RenvoiMailConfirm, PasswordResetCustomView, ProfilPublicView)
from core.views.instance import SendMailVerifInstance
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from core.views.logs_SMTP import ListLogUser, LogsDetailView, ResolutionLog
from portail.views.index import HomePage
from forum.forum_conversation.view import ForumAbonnementMultiUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/login/', login, name='account_login'),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/password/reset/', PasswordResetCustomView.as_view(), name='password_reset_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('profile/<int:pk>/', ProfilPublicView.as_view(), name='profile_publique'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('accounts/profile/gerer_mes_abonnements', ForumAbonnementMultiUpdateView.as_view(), name='gerer_mes_abonnements'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    re_path('core/instance/(?P<pk>\d+)/', SendMailVerifInstance.as_view(), name='verif_mail_instance'),
    path('carto/', include('carto.urls')),
    path('instructions/', include('instructions.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('evenements.urls')),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('o/applications/', HttpResponseForbidden, name="creaapp"),  # surcharge d'oauth pour eviter la création d'application
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path(r'webpush/', include('webpush.urls')),
    path('forum/', include(machina_urls), name='forum'),
    path('list_logs/', ListLogUser.as_view(), name='list_logs'),
    path('detail_log/<int:pk>/', LogsDetailView.as_view(), name='detail_log'),
    path('detail_log/upd/<int:pk>/', ResolutionLog.as_view(), name='resolution_log'),
    path('structure/', include('structure.urls'), name='structure.urls'),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_dynamicurlpatterns(settings.STATIC_ROOT_URL)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

forum/core/urls.py
"""
    Machina core URL helpers
    ========================

    This module defines commons URLs helpers and abstractions used by django-machina to manage its
    URL patterns.

"""


class URLPatternsFactory:
    """ Allows to generate the URL patterns of a machina application.

    Machina's views and URLs use a tree of ``URLPatternsFactory`` instances in order to build the
    complete list of URL patterns of the forum application. This class provides a
    ``get_urlpatterns`` method that allows to define the URL patterns to include in the global list
    of URLs associated with the forum application. This behavior allows to easily override each of
    the views used to build the final list of URL patterns (because the views are imported
    dynamically). It also allows to append additional URLs to the generated URL patterns by
    subclassing the ``URLPatternsFactory`` subclass associated with the considered forum app.

    """

    app_namespace = None

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application.

        This method should be implemented in any subclass.
        """
        return []

    @property
    def urlpatterns(self):
        """ Returns a tuple containing the list of URL patterns and an app namespace. """
        return self.get_urlpatterns(), self.app_namespace

forum/forum_conversation/urls.py
from django.urls import include, path

from .view import PostDeleteView, PostCreateView, TopicCreateView, SignalCreateView, ForumAbonnementCreateView, \
                  ForumAbonnementUpdateView, ForumAbonnementSujetAjax, TopicView, TopicUpdateView, ListStickyTopic, \
                  ListTopicSuiviDeploiement, PostUpdateView, RechercheTopicView
from forum.core.urls import URLPatternsFactory
from forum.forum_conversation.forum_attachments.urls import urlpatterns_factory as attachments_urlpatterns_factory
from forum.forum_conversation.forum_polls.urls import urlpatterns_factory as polls_urlpatterns_factory


class BaseForumConversationURLPatternsFactory(URLPatternsFactory):
    app_namespace = 'forum_conversation'

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """

        conversation_urlpatterns = [
            path('topic/<str:slug>-<int:pk>/', TopicView.as_view(), name='topic',),
            path('topic/create/', TopicCreateView.as_view(), name='topic_create'),
            path('topic/<str:slug>-<int:pk>/update/', TopicUpdateView.as_view(), name='topic_update'),
            path('topic/<str:topic_slug>-<int:topic_pk>/post/create/', PostCreateView.as_view(), name='post_create'),
            path('topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/update/', PostUpdateView.as_view(), name='post_update'),
            path('topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/delete/', PostDeleteView.as_view(), name='post_delete'),
            path('topic/<str:topic_slug>-<int:topic_pk>/<int:pk>/post/signal/', SignalCreateView.as_view(), name='signal_create'),
            path('abonnement-forum/', ForumAbonnementCreateView.as_view(), name='forum_abonnement'),
            path('gerer-abonnement-forum/<pk>/<multiple>/', ForumAbonnementUpdateView.as_view(), name='gerer_forum_abonnement'),
            path('abonnement-sujet/', ForumAbonnementSujetAjax.as_view(), name='abonnement_sujet'),
            path('recherche-sujet/', RechercheTopicView.as_view(), name='recherche_sujet'),

        ]

        urlpatterns = [
            path('<str:forum_slug>-<int:forum_pk>/', include(conversation_urlpatterns),),
            path('forum/<str:forum_slug>-<int:forum_pk>/', include(conversation_urlpatterns), ),
            path('liste-sticky-topic', ListStickyTopic.as_view(), name='sujets-epingles'),
            path('liste-topic-suivi-deploiement', ListTopicSuiviDeploiement.as_view(), name='sujets-suivi-deploiement'),
        ]

        urlpatterns += super().get_urlpatterns()

        return urlpatterns


class ForumAttachmentsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    attachments_urlpatterns_factory = attachments_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.attachments_urlpatterns_factory.urlpatterns)),
        ]


class ForumPollsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_attachments`` application. """

    polls_urlpatterns_factory = polls_urlpatterns_factory

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return super().get_urlpatterns() + [
            path('', include(self.polls_urlpatterns_factory.urlpatterns)),
        ]


class ForumConversationURLPatternsFactory(
    BaseForumConversationURLPatternsFactory, ForumAttachmentsURLPatternsFactory,
    ForumPollsURLPatternsFactory,
):
    """ Composite class combining conversation views with polls & attachments views. """


urlpatterns_factory = ForumConversationURLPatternsFactory()

forum/forum_moderation/urls.py
"""
    Forum moderation URLs
    =====================

    This module defines URL patterns associated with the django-machina's ``forum_moderation``
    application.

"""

from django.urls import path

from forum.core.urls import URLPatternsFactory
from .views import *


class ForumModerationURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_moderation`` application. """

    app_namespace = 'forum_moderation'

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'topic/<str:slug>-<int:pk>/lock/',
                TopicLockView.as_view(),
                name='topic_lock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/unlock/',
                TopicUnlockView.as_view(),
                name='topic_unlock',
            ),
            path(
                'topic/<str:slug>-<int:pk>/delete/',
                TopicDeleteView.as_view(),
                name='topic_delete',
            ),
            path(
                'topic/<str:slug>-<int:pk>/move/',
                TopicMoveView.as_view(),
                name='topic_move',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/topic/',
                TopicUpdateToNormalTopicView.as_view(),
                name='topic_update_to_post',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/sticky/',
                TopicUpdateToStickyTopicView.as_view(),
                name='topic_update_to_sticky',
            ),
            path(
                'topic/<str:slug>-<int:pk>/change/announce/',
                TopicUpdateToAnnounceView.as_view(),
                name='topic_update_to_announce',
            ),
            path('queue/',
                 ModerationQueueListView.as_view(),
                 name='queue'),
            path(
                'queue/<int:pk>/',
                ModerationQueueDetailView.as_view(),
                name='queued_post',
            ),
            path(
                'queue/<int:pk>/approve/',
                PostApproveView.as_view(),
                name='approve_queued_post',
            ),
            path(
                'queue/<int:pk>/disapprove/',
                PostDisapproveView.as_view(),
                name='disapprove_queued_post',
            ),
            path(
                'topic/<str:slug>-<int:pk>/clore/',
                TopicCloreView.as_view(),
                name='topic_clore',
            ),
            path(
                'topic/<str:slug>-<int:pk>/rouvrir/',
                TopicOuvrirView.as_view(),
                name='topic_ouvrir',
            )
        ]


urlpatterns_factory = ForumModerationURLPatternsFactory()

forum/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.urls import include, re_path

from forum.core.urls import URLPatternsFactory
from forum.forum.urls import urlpatterns_factory as forum_urlpatterns_factory
from forum.forum_conversation.urls import urlpatterns_factory as conversation_urlpatterns_factory
from forum.forum_tracking.urls import urlpatterns_factory as tracking_urlpatterns_factory
from forum.forum_moderation.urls import urlpatterns_factory as moderation_urlpatterns_factory
from forum.forum_feeds.urls import urlpatterns_factory as feeds_urlpatterns_factory
from forum.forum_member.urls import urlpatterns_factory as member_urlpatterns_factory

class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    # forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    # conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    # feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    # member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    # moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    # search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    # tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            re_path(r'', include(forum_urlpatterns_factory.urlpatterns)),
            re_path(r'', include(conversation_urlpatterns_factory.urlpatterns)),
            re_path(r'^feeds/', include(feeds_urlpatterns_factory.urlpatterns)),
            re_path(r'^member/', include(member_urlpatterns_factory.urlpatterns)),
            re_path(r'^moderation/', include(moderation_urlpatterns_factory.urlpatterns)),
            # re_path(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            re_path(r'^tracking/', include(tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

forum/templates/forum_conversation/partials/post_form.html
{% load i18n %}
{% load role_tags %}
{% if post_form.non_field_errors %}
{% for error in post_form.non_field_errors %}
<div class="alert alert-danger">
  <i class="icon-exclamation-sign"></i> {{ error }}
</div>
{% endfor %}
{% endif %}

{% include "partials/form_field.html" with field=post_form.subject %}
{% include "partials/form_field.html" with field=post_form.demande_assistance %}
{% if post_form.topic and not post_form.topic.dossier %}
    {% include "partials/form_field.html" with field=post_form.dossier %}
{% endif %}
{% include "partials/form_field.html" with field=post_form.content %}

{% if post_form.username %}
    {% include "partials/form_field.html" with field=post_form.username %}
{% endif %}
{% if post_form.update_reason %}
    {% include "partials/form_field.html" with field=post_form.update_reason %}
{% endif %}
{% if user.is_agent_service_instructeur or user.is_superuser or user|hasgroup:"_support" %}
<!-- Sub "forms" tabs -->

    {% if attachment_formset %}
        <a class="m-2 mb-2" data-bs-toggle="collapse" href="#attachments" role="button" aria-expanded="false" aria-controls="attachments"><i class="ajouter"></i>Ajouter un fichier</a>
        <div class="collapse" id="attachments">
            <div class="form-group mb-2 ms-2">
                <br />
                <div class="row">
                    <div id="attachment_formset" class="col-md-12">
                        {% include "forum_conversation/forum_attachments/attachment_formset.html" %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endif %}
{% if demande_assistance %}
<p class="mt-2 mb-0 alert alert-info">Cette demande va être adressée
    {% if type_destinataire == "préfecture" %}
        au service : {{ destinataire_assistance }}
    {% elif type_destinataire == "administrateur" %}
        aux administrateurs d'instance : {% for admin in destinataire_assistance %}{{ admin }}{% if forloop.last %}.{% else %}, {% endif %}{% endfor %}
    {% elif type_destinataire == "support" %}
        à l'équipe support.
    {% endif %}
</p>
    {% if not post_form.topic.dossier %}
    <script>
    // S'il s'agit d'une demande d'assistance et qu'aucun dossier n'est renseigné, affiche une alert de confirmation
    if(!$("#id_dossier").val()){
        var form = $('form')
        var confirmation = false
        form.submit(function (e){
            if($("#id_dossier").val() === "") {
                if (!confirmation) {
                    if (confirm('Confirmez vous que le sujet n\'est pas lié à un dossier ?')) {
                        confirmation = true
                        form.submit()
                    }
                    form.removeAttr("disabled")
                    form.attr("value", "Soumettre")
                    form.find(".prevent_sub_spinner").remove()
                }
            }
        })
    }
    </script>
    {% endif %}
{% endif %}

forum/templates/forum_conversation/partials/topic_detail_actions.html
{% load i18n %}
{% load forum_permission_tags %}

{% get_permission 'can_add_post' topic request.user as user_can_add_post %}
{% get_permission 'can_subscribe_to_topic' topic request.user as user_can_subscribe_to_topic %}
{% get_permission 'can_unsubscribe_from_topic' topic request.user as user_can_unsubscribe_from_topic %}
{% get_permission 'can_lock_topics' topic.forum request.user as user_can_lock_topics %}
{% get_permission 'can_move_topics' topic.forum request.user as user_can_move_topics %}
{% get_permission 'can_resolve_topics' topic request.user as user_can_resolve_topics %}
{% get_permission 'can_delete_topics' topic.forum request.user as user_can_delete_topics %}
{% get_permission 'can_update_topics_to_normal_topics' topic.forum request.user as user_can_change_to_normal_topics %}
{% get_permission 'can_update_topics_to_sticky_topics' topic.forum request.user as user_can_change_to_sticky_topics %}
{% get_permission 'can_update_topics_to_announces' topic.forum request.user as user_can_change_to_announces %}

{% if not request.user.is_new %}
    {% if not topic.deplace and user_can_add_post or user == topic.poster %}
        <a href="{% url 'forum_conversation:post_create' forum.slug forum.pk topic.slug topic.pk %}" class="btn btn-primary btn-sm"><i class="fa fa-comment fa-lg"></i>&nbsp;{% trans "Post reply" %}</a>
        {% if request.user.is_agent_service_instructeur %}
        <a href="{% url 'forum_conversation:post_create' forum.slug forum.pk topic.slug topic.pk %}?demande_assistance=True" class="btn btn-primary btn-sm"><i class="fa-solid fa-truck-tow"></i>&nbsp;Demander une assistance</a>
        {% endif %}
    {% endif %}
{% else %}
    <a class="btn btn-primary btn-sm"
       onclick="alert('Vous devez être inscrit depuis plus de 24h pour poster un message.')">
        <i class="fa fa-comment fa-lg"></i>&nbsp;{% trans "Post reply" %}</a>
{% endif %}

{% if user_can_lock_topics and not topic.is_locked or user_can_move_topics or user_can_delete_topics or user_can_resolve_topics %}
    <div class="btn-group moderation-dropdown">
        <button id="id_dropdown_moderation_menu_button" class="btn btn-warning btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-gavel">&nbsp;&nbsp;</i><span class="caret"></span></button>
        <div class="dropdown-menu" aria-labelledby="id_dropdown_moderation_menu_button" style="min-width:13rem;">
            {% if user_can_lock_topics and not topic.is_locked %}<a href="{% url 'forum_moderation:topic_lock' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="masquer mr-2"></i> Rendre confidentiel</a>{% endif %}
            {% if user_can_lock_topics and topic.is_locked %}<a href="{% url 'forum_moderation:topic_unlock' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="afficher mr-2"></i>Rendre public</a>{% endif %}
            {% if user_can_delete_topics %}<a href="{% url 'forum_moderation:topic_delete' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="supprimer mr-2"></i>Supprimer le sujet</a>{% endif %}
            {% if user_can_move_topics %}<a href="{% url 'forum_moderation:topic_move' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-arrows-alt-v fa-fw mr-2"></i>Déplacer le sujet</a>{% endif %}
            {% if user_can_resolve_topics and not topic.is_clot %}<a href="{% url 'forum_moderation:topic_clore' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-check fa-fw mr-2"></i>Clore le sujet</a>{% endif %}
            {% if user_can_resolve_topics and topic.is_clot %}<a href="{% url 'forum_moderation:topic_ouvrir' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-door-open fa-fw mr-2"></i>Rouvrir le sujet</a>{% endif %}

            {% if topic.is_topic %}
                {% if user_can_change_to_sticky_topics %}<a href="{% url 'forum_moderation:topic_update_to_sticky' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-lightbulb fa-fw mr-2"></i>Épingler le sujet</a>{% endif %}
                {% if user_can_change_to_announces %}<a href="{% url 'forum_moderation:topic_update_to_announce' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-bullhorn fa-fw mr-2"></i>Changer en annonce</a>{% endif %}
            {% elif topic.is_sticky %}
                {% if user_can_change_to_normal_topics %}<a href="{% url 'forum_moderation:topic_update_to_post' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-bullseye fa-fw mr-2"></i>Changer en sujet standard</a>{% endif %}
                {% if user_can_change_to_announces %}<a href="{% url 'forum_moderation:topic_update_to_announce' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-bullhorn fa-fw mr-2"></i>Changer en annonce</a>{% endif %}
            {% elif topic.is_announce %}
                {% if user_can_change_to_normal_topics %}<a href="{% url 'forum_moderation:topic_update_to_post' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-bullseye fa-fw mr-2"></i>Changer en sujet standard</a>{% endif %}
                {% if user_can_change_to_sticky_topics %}<a href="{% url 'forum_moderation:topic_update_to_sticky' slug=topic.slug pk=topic.pk %}" class="dropdown-item"><i class="fal fa-lightbulb fa-fw mr-2"></i>Épingler le sujet</a>{% endif %}
            {% endif %}
        </div>
    </div>
{% endif %}