api/urls.py
from django.urls import include, path, re_path

from api.views.carto import PoiView
from api.views.viewsets import OrganisateurViewSet, SiteN2KViewSet
from api.views.manif import ManifestationViewSet, ManifPublicViewSet, ManifEnvViewSet
from api.views.instruction import InstructionViewSet
from api.views.avis import AvisView
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


app_name = 'api'
router = routers.DefaultRouter()
router.register(r'Calendrier', ManifPublicViewSet, basename='Calendrier')
router.register(r'Organisateur', OrganisateurViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'Evenement', ManifestationViewSet, basename='Evenement')
router.register(r'Avis', AvisView, basename='Avis')
router.register(r'Evenement_environnement', ManifEnvViewSet, basename='Evenement_environnement')
router.register(r'SiteN2K', SiteN2KViewSet, basename='SiteN2K')
router.register(r'Pois', PoiView, basename='Pois')

schema_view = get_schema_view(
    openapi.Info(
        title="API de manifestationSportive.fr",
        default_version='v1',
        description="Permet l'utilisation de la plateforme à partir d'une autre application\n"
                    "Les urls affichées sont celles que vous pouvez accèder",
        contact=openapi.Contact(name="Openscop", url="https://www.openscop.fr/", email="contact@openscop.fr"),
        license=openapi.License(name="Creative Commons BY-NC-ND 4.0", url="https://creativecommons.org/licenses/by-nc-nd/4.0/")
    ),
    public=False,
    patterns=[path('api/', include(router.urls))],
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include(router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

configuration/urls.py
from forum.urls import urlpatterns as machina_urls

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest, HttpResponseForbidden

from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from core.util.dynamic_static import staticfiles_dynamicurlpatterns
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview, login,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView,
                             RenvoiMailConfirm, PasswordResetCustomView, ProfilPublicView)
from core.views.instance import SendMailVerifInstance
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from core.views.logs_SMTP import ListLogUser, LogsDetailView, ResolutionLog
from portail.views.index import HomePage
from forum.forum_conversation.view import ForumAbonnementMultiUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/login/', login, name='account_login'),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/password/reset/', PasswordResetCustomView.as_view(), name='password_reset_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('profile/<int:pk>/', ProfilPublicView.as_view(), name='profile_publique'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('accounts/profile/gerer_mes_abonnements', ForumAbonnementMultiUpdateView.as_view(), name='gerer_mes_abonnements'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    re_path('core/instance/(?P<pk>\d+)/', SendMailVerifInstance.as_view(), name='verif_mail_instance'),
    path('carto/', include('carto.urls')),
    path('instructions/', include('instructions.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('evenements.urls')),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('o/applications/', HttpResponseForbidden, name="creaapp"),  # surcharge d'oauth pour eviter la création d'application
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path(r'webpush/', include('webpush.urls')),
    path('forum/', include(machina_urls), name='forum'),
    path('list_logs/', ListLogUser.as_view(), name='list_logs'),
    path('detail_log/<int:pk>/', LogsDetailView.as_view(), name='detail_log'),
    path('detail_log/upd/<int:pk>/', ResolutionLog.as_view(), name='resolution_log'),
    path('structure/', include('structure.urls'), name='structure.urls'),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_dynamicurlpatterns(settings.STATIC_ROOT_URL)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

forum/core/urls.py
"""
    Machina core URL helpers
    ========================

    This module defines commons URLs helpers and abstractions used by django-machina to manage its
    URL patterns.

"""


class URLPatternsFactory:
    """ Allows to generate the URL patterns of a machina application.

    Machina's views and URLs use a tree of ``URLPatternsFactory`` instances in order to build the
    complete list of URL patterns of the forum application. This class provides a
    ``get_urlpatterns`` method that allows to define the URL patterns to include in the global list
    of URLs associated with the forum application. This behavior allows to easily override each of
    the views used to build the final list of URL patterns (because the views are imported
    dynamically). It also allows to append additional URLs to the generated URL patterns by
    subclassing the ``URLPatternsFactory`` subclass associated with the considered forum app.

    """

    app_namespace = None

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application.

        This method should be implemented in any subclass.
        """
        return []

    @property
    def urlpatterns(self):
        """ Returns a tuple containing the list of URL patterns and an app namespace. """
        return self.get_urlpatterns(), self.app_namespace

forum/forum/urls.py
from django.urls import path

from forum.core.urls import URLPatternsFactory

from .views import RedirectForumAdminInstance, IndexView, ForumView, SuivieSujetsNonClosView


class ForumURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum`` application. """

    app_namespace = 'forum'

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('', IndexView.as_view(), name='index'),
            path('suivi/', SuivieSujetsNonClosView.as_view(), name="suivi_sujet"),
            path(
                '<str:slug>-<int:pk>/',
                ForumView.as_view(),
                name='forum',
            ),
            path('forum-administrateur-instance', RedirectForumAdminInstance.as_view(), name="forum-redirect")
        ]


urlpatterns_factory = ForumURLPatternsFactory()

forum/forum_feeds/urls.py
"""
    Forum feeds URLs
    ================

    This module defines URL patterns associated with the django-machina's ``forum_feeds``
    application.

"""

from django.urls import path

from forum.core.loading import get_class
from forum.core.urls import URLPatternsFactory


class ForumFeedsURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_feeds`` application. """

    app_namespace = 'forum_feeds'

    latest_topics_feed = get_class('forum_feeds.feeds', 'LastTopicsFeed')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path('topics/', self.latest_topics_feed(), name='latest_topics'),
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/topics/',
                self.latest_topics_feed(),
                name='forum_latest_topics',
            ),
            path(
                'forum/<str:forum_slug>-<int:forum_pk>/topics/all/',
                self.latest_topics_feed(),
                {'descendants': True},
                name='forum_latest_topics_with_descendants',
            ),
        ]


urlpatterns_factory = ForumFeedsURLPatternsFactory()

forum/forum_tracking/urls.py
"""
    Forum tracking URLs
    ===================

    This module defines URL patterns associated with the django-machina's ``forum_tracking``
    application.

"""

from django.urls import path

from forum.core.urls import URLPatternsFactory
from forum.forum_tracking.views import MarkForumsReadView, MarkTopicsReadView, UnreadTopicsView


class ForumTrackingURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the ``forum_search`` application. """

    app_namespace = 'forum_tracking'

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            path(
                'mark/forums/',
                MarkForumsReadView.as_view(),
                name='mark_all_forums_read',
            ),
            path(
                'mark/forums/<int:pk>/',
                MarkForumsReadView.as_view(),
                name='mark_subforums_read',
            ),
            path(
                'mark/forum/<int:pk>/topics/',
                MarkTopicsReadView.as_view(),
                name='mark_topics_read',
            ),
            path(
                'unread-topics/',
                UnreadTopicsView.as_view(),
                name='unread_topics',
            ),
        ]


urlpatterns_factory = ForumTrackingURLPatternsFactory()

forum/urls.py
"""
    Machina URLs
    ============

    This module imports all the URLs defined by the forum-related applications.

"""

from django.urls import include, re_path

from forum.core.urls import URLPatternsFactory
from forum.forum.urls import urlpatterns_factory as forum_urlpatterns_factory
from forum.forum_conversation.urls import urlpatterns_factory as conversation_urlpatterns_factory
from forum.forum_tracking.urls import urlpatterns_factory as tracking_urlpatterns_factory
from forum.forum_moderation.urls import urlpatterns_factory as moderation_urlpatterns_factory
from forum.forum_feeds.urls import urlpatterns_factory as feeds_urlpatterns_factory
from forum.forum_member.urls import urlpatterns_factory as member_urlpatterns_factory

class BoardURLPatternsFactory(URLPatternsFactory):
    """ Allows to generate the URL patterns of the whole forum application. """

    # forum_urlpatterns_factory = get_class('forum.urls', 'urlpatterns_factory')
    # conversation_urlpatterns_factory = get_class('forum_conversation.urls', 'urlpatterns_factory')
    # feeds_urlpatterns_factory = get_class('forum_feeds.urls', 'urlpatterns_factory')
    # member_urlpatterns_factory = get_class('forum_member.urls', 'urlpatterns_factory')
    # moderation_urlpatterns_factory = get_class('forum_moderation.urls', 'urlpatterns_factory')
    # search_urlpatterns_factory = get_class('forum_search.urls', 'urlpatterns_factory')
    # tracking_urlpatterns_factory = get_class('forum_tracking.urls', 'urlpatterns_factory')

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application. """
        return [
            re_path(r'', include(forum_urlpatterns_factory.urlpatterns)),
            re_path(r'', include(conversation_urlpatterns_factory.urlpatterns)),
            re_path(r'^feeds/', include(feeds_urlpatterns_factory.urlpatterns)),
            re_path(r'^member/', include(member_urlpatterns_factory.urlpatterns)),
            re_path(r'^moderation/', include(moderation_urlpatterns_factory.urlpatterns)),
            # re_path(r'^search/', include(self.search_urlpatterns_factory.urlpatterns)),
            re_path(r'^tracking/', include(tracking_urlpatterns_factory.urlpatterns)),
        ]


urlpatterns_factory = BoardURLPatternsFactory()
urlpatterns = urlpatterns_factory.get_urlpatterns()

forum/forms/widgets.py
from django.forms.widgets import Textarea, Select


class SelectWithDisabled(Select):
    """ Subclass of Django's select widget that allows disabling options.

    To disable an option, pass a dict instead of a string for its label, of the form:

        {'label': 'option label', 'disabled': True}

    """

    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        disabled = False
        if isinstance(label, dict):
            label, disabled = label['label'], label['disabled']
        option_dict = super().create_option(
            name, value, label, selected, index, subindex=subindex, attrs=attrs
        )
        if disabled:
            option_dict['attrs']['disabled'] = 'disabled'
        return option_dict


class MarkdownTextareaWidget(Textarea):

    def render(self, name, value, attrs=None, **kwargs):
        attrs = {} if attrs is None else attrs
        classes = attrs.get('classes', '')
        attrs['class'] = classes + ' machina-mde-markdown'
        return super().render(name, value, attrs, **kwargs)

forum/forum_member/forms.py
# """
#     Forum member forms
#     ==================
#
#     This module defines forms provided by the ``forum_member`` application.
#
# """
# #TODO voire a supprimer
# from django import forms
#
# from forum.conf import settings as machina_settings
# from .models import ForumProfile
#
#
# class ForumProfileForm(forms.ModelForm):
#
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         if not machina_settings.PROFILE_AVATARS_ENABLED:
#             del self.fields["avatar"]
#
#     class Meta:
#         model = ForumProfile
#         fields = ['avatar', 'signature', ]

forum/forum_conversation/forum_attachments/views.py
"""
    Forum attachments views
    =======================

    This module defines views provided by the ``forum_attachments`` application.

"""

import mimetypes
import os

from django.http import HttpResponse
from django.views.generic import DetailView

from forum.forum_conversation.forum_attachments.models import Attachment
from forum.forum_permission.viewmixins import PermissionRequiredMixin


class AttachmentView(PermissionRequiredMixin, DetailView):
    """ Allows to retrieve a forum attachment. """

    model = Attachment

    def render_to_response(self, context, **response_kwargs):
        """ Generates the appropriate response. """
        filename = os.path.basename(self.object.file.name)

        # Try to guess the content type of the given file
        content_type, _ = mimetypes.guess_type(self.object.file.name)
        if not content_type:
            content_type = 'text/plain'

        response = HttpResponse(self.object.file, content_type=content_type)
        response['Content-Disposition'] = 'attachment; filename={}'.format(filename)

        return response

    def get_controlled_object(self):
        """ Returns the controlled object. """
        return self.get_object().post.topic.forum

    def perform_permissions_check(self, user, obj, perms):
        """ Performs the permission check. """
        return self.request.forum_permission_handler.can_download_files(obj, user)

forum/templates/forum/forum_detail.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_tags %}
{% load forum_conversation_tags %}
{% load forum_permission_tags %}
{% load forum_tracking_tags %}
{% load verbose_tags %}
{% block head_title %}{{ forum.name }}{% endblock %}
{% block sub-title %}{{ forum.name }}{% endblock sub-title %}

{% block content %}
    {% if forum.is_forum %}

        <div id="hacker-list">
        <div class="mt-4 mb-3  mb-2">
            <div class="forum-actions-block d-flex">
                {% get_permission 'can_add_topic' forum request.user as user_can_add_topic %}
                {% if user_can_add_topic %}
                    {% if not request.user.is_new %}
                        <a href="{% url 'forum_conversation:topic_create' forum.slug forum.pk %}" class="btn btn-primary btn-sm"><i class="fa fa-comments fa-lg"></i>Nouveau Sujet</a>
                    {% else %}
                        <a  class="btn btn-primary btn-sm" onclick="alert('Vous devez être inscrit depuis plus de 24h pour poster un message.')">
                            <i class="fa fa-comments fa-lg"></i>Nouveau Sujet</a>
                    {% endif %}
                <input class="filtre-item w-25 h-100 form-control ms-3" id="input-search-forum" placeholder="Recherche"/>
                    {% if not forum_abonnement %}
                        <a href="{% url 'forum_conversation:forum_abonnement' forum.slug forum.pk %}" class="ms-auto btn btn-secondary btn-sm"><i class="fas fa-plus fa-lg"></i>S'abonner à des sujets</a>
                    {% else %}
                        <a href="{% url 'forum_conversation:gerer_forum_abonnement' forum.slug forum.pk forum_abonnement.pk False%}" class="ms-auto float-end btn btn-secondary btn-sm"><i class="fas fa-sliders-h"></i>Gérer mes abonnements</a>
                    {% endif %}
                {% endif %}
            </div>
        </div>

        {% trans "Announcements" as announcements_title_trans %}
        {% with topic_list_title=announcements_title_trans topics=announces hide_if_empty=True unread_topics=unread_topics announcements=True%}
            {% include "forum_conversation/topic_list.html" %}
        {% endwith %}


            <div>
                <div class="d-flex flex-wrap pb-1">
                    <div class="col-1">
                        <p>Filtrer par : </p>
                    </div>
                    <div class="d-flex flex-wrap pb-1 col-11">
                        <div class="filtre-item me-3 mb-2" id="filtre-theme-forum">
                            <select name="statut" id="statut" class="select-filter selectpicker mt-sm-1" data-live-search="true">
                                <option selected="selected" value="">Statut</option>
                                <option value="False"> Ouvert </option>
                                <option value="True"> Clôturer </option>
                            </select>
                        </div>
                        {% if activites %}
                            <div class="filtre-item me-3">
                                <select name="activite" id="activite" class="select-filter selectpicker mt-sm-1" data-live-search="true">
                                    <option selected="selected" value="">Activité</option>
                                    {% for activite in activites %}
                                        <option value="{{ activite }}"> {{ activite.discipline }} / {{ activite }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                        {% if departements %}
                            <div class="filtre-item me-3">
                                <select name="departement" id="departement" class="select-filter selectpicker mt-sm-1" data-live-search="true">
                                    <option selected="selected" value="">Département</option>
                                    {% for departement in departements %}
                                        <option value="{{ departement }}"> {{ departement }} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                        {% if services %}
                            <div class="filtre-item me-3">
                                <select name="service" id="service" class="select-filter selectpicker mt-sm-1" data-live-search="true">
                                    <option selected="selected" value="">Service de l'auteur</option>
                                    {% for service in services %}
                                        <option value="{{ service.pk }}"> {{ service.nom_s }} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                        {% if departements_user %}
                            <div class="filtre-item me-3">
                                <select name="departement_user" id="departement_user" class="select-filter selectpicker mt-sm-1" data-live-search="true">
                                    <option selected="selected" value="">Département de l'auteur</option>
                                    {% for departement in departements_user %}
                                        <option value="{{ departement.pk }}"> {{ departement }} </option>
                                    {% endfor %}
                                </select>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="d-flex pb-2">

                <div class="col-12 d-flex flex-wrap">
                    {% for theme in themes %}
                        <span class="badge sort me-1 mb-1 badge-pill theme-sort" data-theme="{{ theme.pk }}" style="background-color: {{ theme.color }}; font-size: 12px;">{{ theme }}</span>
                    {% endfor %}
                </div>
            </div>




            {% trans "Topics" as topics_title_trans %}
            {% with topic_list_title=topics_title_trans unread_topics=unread_topics %}

                {% include "forum_conversation/topic_list.html" %}
                </div>
            {% endwith %}
        <div class="mt-3 mb-5 row">
            <div class="col-6 col-md-4 forum-actions-block">
                {% if user_can_add_topic %}
                    <a href="{% url 'forum_conversation:topic_create' forum.slug forum.pk %}" class="btn btn-primary btn-sm"><i class="fa fa-comments fa-lg"></i>Nouveau Sujet</a>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock content %}

forum/templates/forum/index.html
{% extends 'board_base.html' %}
{% load i18n %}
{% load forum_tags %}

{% block sub_title %}{% trans "Index" %}{% endblock sub_title %}

{% block content %}
<div class="mt-3 row">
  <div class="forumlist-top-controls col-12 d-flex">
    {% if request.user.is_authenticated %}
    <div class="col-6">
        <a href="{% url 'forum_tracking:mark_all_forums_read' %}" class="d-inline-block"><i class="fas fa-check-circle">&nbsp;</i>{% trans "Mark forums read" %}</a><br>
        <a href="{% url 'forum_tracking:unread_topics' %}" class="d-inline-block">Voir les sujets non lus</a>
    </div>
    <div class="col-6 test-end">

        <a href="{% url 'forum:suivi_sujet' %}" class="btn btn-secondary float-end">
            <i class="fa-sharp fa-solid fa-bullseye-pointer"></i>Suivi des sujets non clos
        </a>
    </div>
    {% endif %}
  </div>
</div>
{% forum_list forums %}
<div class="my-4 row">
  <div class="forum-page-statistics col-12">
    <h4 class="page-header">{% trans "Statistics" %}</h4>
    <p class="statistics">Nombre total de réponse&nbsp;<b>{{ total_posts_count }}</b>&nbsp;&#8226;&nbsp;Nombre total de sujet&nbsp;<b>{{ total_topics_count }}</b>&nbsp;</p>
  </div>
</div>
{% endblock content %}

forum/templates/forum/tableau_topic_non_clos.html
<!--bof forum/tableau_topic_non_clos.html-->
<table class="table rounded-top">
    <thead>
    <tr style="background: #869200; color: white;">
        {% for forum, value in forums_dict.items %}
            <th scope="col" class="py-3" style="border-right: 1px solid #6c757d">
                {{ forum.get_forum_name|title }}
                <a class="link_to_filtered_forum" href="{% url 'forum:forum' forum.slug forum.id %}?dep={{ instance_selected_pk }}#ouvert">
                    <span class="badge bg-secondary ms-2" style="font-size: 0.8rem;">{{ value.total_post }}</span>
                </a>
            </th>
        {% endfor %}
        {% if forums_departemental_dict %}
            <th scope="col" class="py-3" style="border-right: 1px solid #6c757d">
                Administrateur D'Instance Départemental
                <span class="badge bg-secondary ms-2" style="font-size: 0.8rem;">{{ forum_departemental_total }}</span>
            </th>
        {% endif %}
    </tr>
    </thead>
    <tbody>
    {% for forum, value in forums_dict.items %}
        <th scope="col" style="border: 0.5px solid #6c757d; border-top: none !important;">
            {% for theme, value in value.themes.items %}
                <a href="{% url 'forum:forum' forum.slug forum.id %}?dep={{ instance_selected_pk }}#{{ theme.pk }}" class="link_to_filtered_forum">
                    <span class="badge text-white my-1" style="background-color: {{ theme.color }}; font-size: 0.78rem"><span class="me-2">{{ value }}</span>{{ theme }}</span>
                </a>
                <br>
            {% endfor %}
        </th>
    {% endfor %}
    {% if forums_departemental_dict %}
        <th scope="col" style="border: 0.5px solid #6c757d; border-top: none !important;">
            {% for forum, value in forums_departemental_dict.items %}
                <a href="{% url 'forum:forum' forum.slug forum.id %}#ouvert">
                    <span class="badge my-1" style="background-color:  #a8b6bf; font-size: 0.78rem"><span class="me-2 d-inline-block" style="color: #3b3b3b; min-width: 18px">{{ value }}</span>{{ forum.departement }}</span>
                </a>
                <br>
            {% endfor %}
        </th>
    {% endif %}
    </tbody>
</table>
<!-- eof forum/tableau_topic_non_clos.html-->