api/urls.py
from django.urls import include, path, re_path

from api.views.carto import PoiView
from api.views.viewsets import OrganisateurViewSet, SiteN2KViewSet
from api.views.manif import ManifestationViewSet, ManifPublicViewSet, ManifEnvViewSet
from api.views.instruction import InstructionViewSet
from api.views.avis import AvisView
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


app_name = 'api'
router = routers.DefaultRouter()
router.register(r'Calendrier', ManifPublicViewSet, basename='Calendrier')
router.register(r'Organisateur', OrganisateurViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'Evenement', ManifestationViewSet, basename='Evenement')
router.register(r'Avis', AvisView, basename='Avis')
router.register(r'Evenement_environnement', ManifEnvViewSet, basename='Evenement_environnement')
router.register(r'SiteN2K', SiteN2KViewSet, basename='SiteN2K')
router.register(r'Pois', PoiView, basename='Pois')

schema_view = get_schema_view(
    openapi.Info(
        title="API de manifestationSportive.fr",
        default_version='v1',
        description="Permet l'utilisation de la plateforme à partir d'une autre application\n"
                    "Les urls affichées sont celles que vous pouvez accèder",
        contact=openapi.Contact(name="Openscop", url="https://www.openscop.fr/", email="contact@openscop.fr"),
        license=openapi.License(name="Creative Commons BY-NC-ND 4.0", url="https://creativecommons.org/licenses/by-nc-nd/4.0/")
    ),
    public=False,
    patterns=[path('api/', include(router.urls))],
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include(router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

configuration/urls.py
from forum.urls import urlpatterns as machina_urls

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest, HttpResponseForbidden

from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from core.util.dynamic_static import staticfiles_dynamicurlpatterns
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview, login,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView,
                             RenvoiMailConfirm, PasswordResetCustomView, ProfilPublicView)
from core.views.instance import SendMailVerifInstance
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from core.views.logs_SMTP import ListLogUser, LogsDetailView, ResolutionLog
from portail.views.index import HomePage
from forum.forum_conversation.view import ForumAbonnementMultiUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/login/', login, name='account_login'),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/password/reset/', PasswordResetCustomView.as_view(), name='password_reset_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('profile/<int:pk>/', ProfilPublicView.as_view(), name='profile_publique'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('accounts/profile/gerer_mes_abonnements', ForumAbonnementMultiUpdateView.as_view(), name='gerer_mes_abonnements'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    re_path('core/instance/(?P<pk>\d+)/', SendMailVerifInstance.as_view(), name='verif_mail_instance'),
    path('carto/', include('carto.urls')),
    path('instructions/', include('instructions.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('evenements.urls')),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('o/applications/', HttpResponseForbidden, name="creaapp"),  # surcharge d'oauth pour eviter la création d'application
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path(r'webpush/', include('webpush.urls')),
    path('forum/', include(machina_urls), name='forum'),
    path('list_logs/', ListLogUser.as_view(), name='list_logs'),
    path('detail_log/<int:pk>/', LogsDetailView.as_view(), name='detail_log'),
    path('detail_log/upd/<int:pk>/', ResolutionLog.as_view(), name='resolution_log'),
    path('structure/', include('structure.urls'), name='structure.urls'),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_dynamicurlpatterns(settings.STATIC_ROOT_URL)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

forum/core/urls.py
"""
    Machina core URL helpers
    ========================

    This module defines commons URLs helpers and abstractions used by django-machina to manage its
    URL patterns.

"""


class URLPatternsFactory:
    """ Allows to generate the URL patterns of a machina application.

    Machina's views and URLs use a tree of ``URLPatternsFactory`` instances in order to build the
    complete list of URL patterns of the forum application. This class provides a
    ``get_urlpatterns`` method that allows to define the URL patterns to include in the global list
    of URLs associated with the forum application. This behavior allows to easily override each of
    the views used to build the final list of URL patterns (because the views are imported
    dynamically). It also allows to append additional URLs to the generated URL patterns by
    subclassing the ``URLPatternsFactory`` subclass associated with the considered forum app.

    """

    app_namespace = None

    def get_urlpatterns(self):
        """ Returns the URL patterns managed by the considered factory / application.

        This method should be implemented in any subclass.
        """
        return []

    @property
    def urlpatterns(self):
        """ Returns a tuple containing the list of URL patterns and an app namespace. """
        return self.get_urlpatterns(), self.app_namespace

structure/urls.py
from django.urls import path

from .views.ajax import *
from .views.administration_des_services import *
from .views.edition_organisation_graphique import EditionOrganisationGraphique, EditionOrganisationGraphiqueAjax
from .views.interaction import *
from .views.modification_champ_service import *
from .views.user import *
from .views.fusion_service import FusionServiceView
from .views.cdsr import *

app_name = 'structure'
urlpatterns = [
    path('fiche-organisation/<pk>/', FicheOrganisationView.as_view(), name='fiche_organisation'),
    path('liste/types_service/', ListeTypeServiceView.as_view(), name='liste_types_service'),
    path('administration_des_services/', AdministrationServiceView.as_view(), name='administration_des_services'),
    path('liste_user_sans_service/', UserSansServiceListView.as_view(), name='liste_user_sans_service'),
    path('comptes_dormants/', ComptesDormantsView.as_view(), name='comptes_dormants'),

    path('administration_des_services/is_admin_famille/', IsAdminFamilleAjaxView.as_view(), name="is_admin_famille"),
    path('administration_des_services/is_habilite/<pk>/', IsHabiliteAjaxView.as_view(), name="is_famille"),

    path('update_service_consulte_active/<pk>/', ServiceConsulteUpdateActiveView.as_view(), name="update_service_consulte_active"),
    path('update_service_consulte_instance/<pk>/', ServiceConsulteUpdateInstanceView.as_view(), name="update_service_consulte_instance"),
    path('update_service_consulte_site/<pk>/', ServiceConsulteUpdateSiteView.as_view(), name="update_service_consulte_site"),
    path('update_service_consulte_action/<pk>/', ServiceConsulteUpdateActionView.as_view(), name="update_service_consulte_action"),
    path('update_service_consulte_nom/<pk>/', ServiceConsulteUpdateNomView.as_view(), name="update_service_consulte_nom"),
    path('update_service_consulte_type/<pk>/', ServiceConsulteUpdateTypeView.as_view(), name="update_service_consulte_type"),
    path('update_service_consulte_parent/<pk>/', ServiceConsulteUpdateParentView.as_view(), name="update_service_consulte_parent"),
    path('update_service_consulte_secteur/<pk>/', ServiceConsulteUpdateSecteurView.as_view(), name="update_service_consulte_secteur"),
    path('update_service_consulte_adresse/<pk>/', ServiceConsulteUpdateAdresseView.as_view(), name="update_service_consulte_adresse"),
    path('update_service_consulte_email/<pk>/', ServiceConsulteUpdateEmailView.as_view(), name="update_service_consulte_email"),
    path('update_service_consulte_telephone/<pk>/', ServiceConsulteUpdateTelephoneView.as_view(), name="update_service_consulte_telephone"),
    path('update_service_consulte_delai_avis/<pk>/', ServiceConsulteUpdateDelaiAvisView.as_view(), name="update_service_consulte_delai_avis"),
    path('update_service_consulte_delai_preavis/<pk>/', ServiceConsulteUpdateDelaiPreavisView.as_view(), name="update_service_consulte_delai_preavis"),

    path('update_user_email/<pk>/', UserUpdateEmailView.as_view(), name="update_user_email"),
    path('delete_user_email/', UserDeleteEmailView.as_view(), name="delete_user_email"),
    path('update_user_active/<pk>/', UserUpdateActiveView.as_view(), name="update_user_active"),
    path('update_user_organisation/<service_id>/<pk>/', UserOrganisationnUpdateView.as_view(), name="update_user_organisation"),
    path('remove_user_from_organisation/', RemoveUserOrganisationView.as_view(), name="remove_user_from_organisation"),
    path('add_user_organisation/', AddUserOrganisationView.as_view(), name="add_user_organisation"),
    path('gerer-user-organisation/<pk>/', GererUserOrganisationView.as_view(), name="gerer-user-organisation"),
    path('gerer-membre-cdsr/<pk>/', GererUserOrganisationView.as_view(), name="gerer-membre-cdsr"),

    path('organisation/<pk>/historique/', OrganisationHistoriqueView.as_view(), name='historique_organisation'),
    path('user/<pk>/historique/', UserHistoriqueView.as_view(), name='historique_user'),

    path('create_service_consulte/', ServiceConsulteCreateView.as_view(), name="create_service_consulte"),
    path('create_federation/', FederationCreateView.as_view(), name="create_federation"),
    path('create_service_instructeur/', ServiceInstructeurCreateView.as_view(), name="create_service_instructeur"),
    path('update_structure_organisatrice/<pk>/', StructureOrganisatriceUpdateView.as_view(), name="update_structure_organisatrice"),
    path('create_structure_organisatrice/', StructureOrganisatriceCreateView.as_view(), name="create_structure_organisatrice"),
    path('create_interaction/<service_id>/', ServiceConsulteInteractionCreateView.as_view(), name="create_interaction"),
    path('update_interaction/<service_id>/<pk>/', ServiceConsulteInteractionUpdateView.as_view(), name="update_interaction"),

    path('ajax/delete_interaction/', DeleteInteraction.as_view(), name='delete_interaction'),
    # Widget AJAX
    path('ajax/servicelist/', ServiceListAJAXView.as_view(), name='service_list'),
    path('ajax/categorielist/', CategorieListAJAXView.as_view(), name='categorie_list'),
    path('ajax/agentlist/', AgentListAjaxView.as_view(), name='agent_list'),
    path('ajax/sous_service/', SousServiceListAjaxView.as_view(), name='sous_service_list'),
    path('ajax/organisation_detail/', OrganisationDetailAjaxView.as_view(), name='organisation_detail'),
    path('ajax/user_detail/', UserDetailAjaxView.as_view(), name='user_detail'),
    path('ajax/invitation/', InvitationAjaxView.as_view(), name="invitation_inscription"),

    path('fusion_service/<pk_afusion>/', FusionServiceView.as_view(), name="fusion_service"),
    path('edition_organisation/<pk_organisation>/', EditionOrganisationGraphique.as_view(), name="edition_organisation"),
    path('update_service_consulte_action/<pk>/', ServiceConsulteUpdateActionView.as_view(), name="update_service_consulte_action"),
    path('ajax/edition_organisation/<pk_organisation>/', EditionOrganisationGraphiqueAjax.as_view(), name='edition_organisation_ajax'),

    path('CDSR/liste/', ReunionCDSRListView.as_view(), name="reunionCDSR_list"),
    path('CDSR/add', ReunionCDSRCreateView.as_view(), name="reunionCDSR_create"),
    path('CDSR/<pk>/', ReunionCDSRDetailView.as_view(), name="reunionCDSR_detail"),
    path('CDSR/<pk>/update', ReunionCDSRUpdateView.as_view(), name="reunionCDSR_update"),
    path('CDSR/<pk>/delete', ReunionCDSRDeleteView.as_view(), name="reunionCDSR_delete"),
    path('CDSR/<pk>/convoquer', ReunionCDSRConvoquerView.as_view(), name="reunionCDSR_convoquer"),
    path('ServiceCDSR/<pk>/add', ServiceCDSRAddMemberAjaxView.as_view(), name="ajouter_membre_cdsr_ajax"),
    path('ServiceCDSR/<pk>/delete', ServiceCDSRDeleteMemberAjaxView.as_view(), name="retirer_membre_cdsr_ajax"),
    path('CDSR/presentation/<pk>/delete', PresentationCDSRDeleteView.as_view(), name="presentationcdsr_remove"),
    path('CDSR/presentation/<pk>/date/reset', PresentationCDSRDateResetView.as_view(), name="presentationcdsr_reset_date"),
    path('CDSR/presentation/<pk>/date/set', PresentationCDSRDateSetView.as_view(), name="presentationcdsr_set_date"),
    path('CDSR/presentation/<pk>/heure/set', PresentationCDSRHeureSetView.as_view(), name="presentationcdsr_set_heure"),
    path('CDSR/presentation/<pk>/convoquer', PresentationCDSRConvoquerView.as_view(), name="presentationcdsr_convoquer"),
    path('CDSR/presentation/<pk>/confirmer', PresentationCDSRConfirmerView.as_view(), name="presentationcdsr_confirmer"),
    path('CDSR/presentation/<pk>/invite/add', PresentationCDSRInviteAddAjaxView.as_view(), name="ajouter_invite_ajax"),
    path('CDSR/presentation/<pk>/invite/delete', PresentationCDSRInviteDeleteAjaxView.as_view(), name="retirer_invite_ajax"),
]

core/models/errorsmtp.py
from django.db import models

from core.models import User, Instance
from structure.models.organisation import Organisation


class ErrorSMTP(models.Model):

    ERROR_CHOICES = (
        # Anti spam
        ('SPA', 'Anti-Spam'),
        # Boite mail inexistante
        ('INC', 'Adresse email inconnue'),
        # Problème hôte
        ('HOT', 'Problème hôte adresse email'),
        # Absent
        ('ABS', 'Utilisateur absent'),
        # Boîte mail pleine
        ('PLE', 'Boîte pleine'),
        # Changement d'adresse
        ('ADR', 'Changement d\'adresse'),
    )

    email = models.EmailField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    instance = models.ForeignKey(Instance, on_delete=models.CASCADE, null=True, blank=True)
    service = models.ForeignKey(Organisation, on_delete=models.SET_NULL, null=True, blank=True)
    type_erreur = models.CharField(max_length=5, choices=ERROR_CHOICES)
    contenu_email = models.TextField(max_length=5000)
    date = models.DateTimeField(auto_now_add=True)
    resolu = models.BooleanField(default=False)

    def __str__(self):
        return self.email

core/views/csrf.py
from django.shortcuts import redirect


def csrf_failure(request, reason=""):
    """
    Changer la vue csrf erreur pour renvoyer sur l'accueil
    """
    return redirect('home_page')

core/templates/core/access_restricted.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}Accès Restreint{% endblock %}
{% block page_title %}
    <h1>Accès restreint</h1>
{% endblock %}

{% block content %}
    <p>{{ message|safe }}</p>
    <p><a href="{% url "home_page" %}" class="btn btn-primary" role="button">Retour à la page d'accueil</a></p>
{% endblock %}

core/templates/core/list_logs.html
{% load static %}
<div class="card" id="logs_list">
    <div class="p-0 card-header">
        <div class="row m-0 px-3 py-2">
            <div class="col-2"><a href="#" class="sort" data-sort="email"><i class="fas fa-sort text-muted"></i>Email</a></div>
            <div class="col-2"><a href="#" class="sort" data-sort="user"><i class="fas fa-sort text-muted"></i>Utilisateur</a></div>
            <div class="col-2"><a href="#" class="sort" data-sort="service"><i class="fas fa-sort text-muted"></i>Service</a></div>
            <div class="col-2"><a href="#" class="sort" data-sort="date"><i class="fas fa-sort text-muted"></i>Date</a></div>
            <div class="col-2"><a href="#" class="sort" data-sort="date"><i class="fas fa-sort text-muted"></i>Type d'erreur</a></div>
        </div>
    </div>
    <div class="p-0 card-body">
        <ul class="list list-group">
            {% for log in logs %}
                <li class="item list-group-item">
                    <div class="row m-0 px-0 ">
                        <div class="col-2"><span class="email">{{ log.email }}</span></div>
                        <div class="col-2"><span class="user">{{ log.user }}</span></div>
                        <div class="col-2"><span class="service">{{ log.service }}</span></div>
                        <div class="col-2"><span class="date" data-timestamp="{{ log.date|date:"U" }}">{{ log.date }}</span></div>
                        <div class="col-2"><span class="type">{{ log.get_type_erreur_display }}</span></div>
                        {% if not detail %}
                            <div class="col-2">
                                <span>
                                    <a href="{% url 'detail_log' log.pk %}">Voir les logs</a>
                                    <a href="{% url 'resolution_log' log.pk %}" class="btn btn-primary ms-2">Résoudre</a>
                                </span>
                            </div>
                        {% endif %}
                    </div>
                </li>
                {% if detail and forloop.last and is_admin %}
                    </ul>
                    </div>
                    <div class="card-footer">
                        <div class="row m-0 p-0">
                            <div class="col-10">
                                <p class="my-3"><a href="{% url 'list_logs' %}">Retour à la liste</a></p>
                            </div>
                            <div class="col-2">
                                    <span class="col-8 float-end">
                                        <a href="{% url 'resolution_log' log.pk %}" class="btn btn-primary mt-2">Résoudre</a>
                                    </span>
                            </div>
                        </div>
                    </div>
                {% elif forloop.last %}
                    </ul>
                    </div>
                {% endif %}

            {% endfor %}

</div>
<script src='{% static "libs/list.min.js" %}' type="text/javascript"></script>
<script>
    var logList = new List('logs_list', {
        valueNames: ['user', 'service', 'email', 'type',{attr: 'data-timestamp', name: 'date'}]
    });
</script>
<script src="{% static "portail/js/sort_button.js" %}" type="text/javascript"></script>

core/templates/core/list_logs_page.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}
    Liste logs
{% endblock %}

{% block page_title %}
    <h1>Liste logs</h1>
{% endblock %}

{% block content %}
    {% include "core/list_logs.html" %}
{% endblock %}

core/templates/core/password_expired.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}
    Mot de passe expiré
{% endblock %}

{% block page_title %}
    <h1>Mot de passe expiré</h1>
{% endblock %}

{% block content %}
    <div class="alert-danger alert">Votre mot de passe a expiré.<br>
        Un email vous a été envoyé pour vous expliquer comment le changer.<br>
        Veuillez consulter votre boite email et suivre les instructions transmises.</div>
{% endblock %}

core/templates/core/user_detail.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% load verbose_tags %}
{% block head_title %}
    Profil
{% endblock %}

{% block page_title %}
    <h1>Profil de {{ object.get_full_name }}  {% if user_is_owner %}<i class="ctx-help-profil"></i>{% endif %}</h1>
{% endblock %}

{% block content %}
    <div class="row">
        <div class=" col-md-6">
            <div class="card position-relative">
                <div class="card-header bg-primary"><i class="utilisateur"></i>Utilisateur</div>
                <div class="card-body">
                    {% include "structure/panneaux/user_information.html" with user=object %}
                    <div class="row mb-2">
                        <div class="col-5 libelle">Dernier changement de mot de passe :</div>
                        <div class="col-7 valeur">{{ object.last_change_password }}
                            {% if user_is_owner %}
                                <a class="float-end" href="{% url 'account_change_password' %}"><i class="editer"></i>Modifier mon mot de passe</a>
                            {% endif %}
                        </div>
                    </div>

                    {% if user_is_owner %}
                        <a class="btn btn-primary btn-action btn-sm" href="{% url 'profile_edit' %}" role="button"><i class="editer"></i>Modifier</a>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-md-6 h-100">
            {% if user_is_owner %}
                <div class="card">
                    <div class="card-header bg-primary"><i class="fas fa-wrench"></i>Paramètres</div>
                    <div class="card-body">
                        <p class="mb-4"><i class="msg_forum"></i>Forum :
                            <a href="{% url 'gerer_mes_abonnements' %}" class="btn btn-primary float-end">
                                <i class="editer"></i>Modifier vos abonnements
                            </a>
                        </p>
                        <p><i class="message"></i>Messagerie :
                            <a href="{% url 'parametre_notification_messagerie' %}" class="btn btn-primary float-end">
                                <i class="editer"></i>Modifier vos options de notifications
                            </a>
                        </p>
                    </div>
                </div>
            {% endif %}
        </div>
        <div class="col-12 mt-3">
            <div class="card">
                <div class="card-header bg-primary"><i class="structure"></i>Organisations</div>
                <ul class="nav nav-tabs card-header">
                    {% for organisation in object.organisation_m2m.all %}
                        <li class="nav-item">
                            <a class="nav-link {% if forloop.first %}active{% endif %}"
                               href="#organisation-tab-{{ organisation.pk }}"
                               data-bs-toggle="tab" role="tab"
                               aria-controls="organisation-tab-{{ organisation.pk }}"
                               aria-selected="false">{{ organisation.nom_s }}</a>
                        </li>
                    {% endfor %}
                </ul>
                <div class="cadre tab-content border-0 p-0" id="ex1-content">
                    {% for organisation in object.organisation_m2m.all %}
                        <div id="organisation-tab-{{ organisation.pk }}"
                             class="tab-pane fade  {% if forloop.first %}show active{% endif %}"
                             role="tabpanel" aria-labelledby="ex1-tab-1">
                            <div class="card">
                                <div class="d-flex card-body flex-wrap">
                                    {% include "structure/panneaux/fiche-organisation-detail.html" %}
                                </div>
                                <div class="card-footer text-center p-3">
                                    {% if organisation.is_structure_organisatrice %}
                                        <a href="{% url 'structure:update_structure_organisatrice' pk=organisation.pk %}" class="btn btn-primary">
                                            <i class="editer"></i>Modifier cette structure
                                        </a>
                                    {% else %}
                                        {% if request.organisation in organisation.get_services_administrateurs or is_admin %}
                                            <a href="{% url 'structure:administration_des_services' %}?service_id={{ organisation.pk }}"
                                               class="btn btn-danger">
                                                <i class="admin-famille"></i>Administrer la famille
                                            </a>
                                        {% elif organisation.get_services_administrateurs and not organisation.is_service_instructeur %}
                                            <a href="{% url 'structure:fiche_organisation' pk=organisation.get_services_administrateurs.first.pk %}"
                                               target="_blank"
                                               class="btn btn-primary">
                                                <i class="admin-famille"></i>Voir le service administrateur de la famille
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

    <script>
        var user_organisation_id = {{ user_organisation.id }};
        var is_admin = "{{ is_admin|yesno:"true,false" }}";
        if(is_admin === "true") {
            is_admin = true;
        } else {
            is_admin = false;
        }
    </script>
    <script src='{% static "structure/invitation.js" %}' type="text/javascript"></script>
    <script src='{% static "structure/administration_des_services.js" %}' type="text/javascript"></script>
{% endblock %}

core/templates/core/user_form.html
{% extends "base_form.html" %}

{% load crispy_forms_tags %}
{% load i18n %}
{% load static %}

{% block head_title %}
    Modification des informations utilisateur
{% endblock %}

{% block page_title %}
    <h1>Modification des informations utilisateur</h1>
{% endblock %}