aide/urls.py
# coding: utf-8
from django.urls import path, re_path

from aide import views


app_name = 'aide'
urlpatterns = [
    # Aide : sommaire
    path('', views.page_aide, {"path": "sommaire"}, name="aide-sommaire"),

    # Aide : liste
    path('liste', views.liste_pages_aide, name="liste-page-aide"),

    # Aide contextuelle
    re_path('context/(?P<name>.+)', views.view_context_help, name="context"),

    # formulaire de demande
    path('contact', views.demande, name="contact"),

    # Aide : page
    re_path('vu/(?P<pk>\d+)/', views.AjoutVuePanelAjax, name="vu-panneau"),
    re_path('(?P<path>[a-zA-Z0-9-/_]+)/(?P<pk>\d+)', views.page_aide, name="page-aide-direct"),
    re_path('(?P<path>.+)', views.page_aide, name="page-aide"),
]

api/urls.py
from django.urls import include, path, re_path
from api.views.organisateur import OrganisateurViewSet
from api.views.manif import ManifestationViewSet, ManifPublicViewSet
from api.views.instruction import InstructionViewSet
from api.views.preavis import PreavisViewSet
from api.views.avis import AvisView
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="API de manifestationSportive.fr",
        default_version='v1',
        description="Permet l'utilisation de la plateforme à partir d'une autre application\n"
                    "Les urls affichées sont celles que vous pouvez accèder",
        contact=openapi.Contact(name="Openscop", url="https://www.openscop.fr/", email="contact@openscop.fr"),
        license=openapi.License(name="Creative Commons BY-NC-ND 4.0", url="https://creativecommons.org/licenses/by-nc-nd/4.0/")
    ),
    public=False,
    permission_classes=(permissions.AllowAny,),
)

app_name = 'api'
router = routers.DefaultRouter()
router.register(r'Calendrier', ManifPublicViewSet, basename='Calendrier')
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'Evenement', ManifestationViewSet, basename='Evenement')
router.register(r'Preavis', PreavisViewSet, basename='Preavis')
router.register(r'Avis', AvisView, basename='Avis')
router.register(r'Organisateur', OrganisateurViewSet)

urlpatterns = [
    path('', include(router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

configuration/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest, HttpResponseForbidden

from django.contrib import admin
from django.contrib.flatpages import views as flatpages_views
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from core.util.dynamic_static import staticfiles_dynamicurlpatterns
from core.views.ajax import validate_form
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView, RenvoiMailConfirm, PasswordResetCustomView, ProfilPublicView)
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from organisateurs.views import StructureUpdateView
from portail.views.index import HomePage

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/password/reset/', PasswordResetCustomView.as_view(), name='password_reset_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('profile/<int:pk>/', ProfilPublicView.as_view(), name='profile_publique'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profile/structure/edit', StructureUpdateView.as_view(), name='structure_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    path('administration/', include('administration.urls')),
    path('agreements/', include('agreements.urls')),
    path('carto/', include('carto.urls')),
    path('sub_agreements/', include('sub_agreements.urls')),
    path('instructions/', include('instructions.urls')),
    path('authorizations/', include('authorizations.urls')),
    path('declarations/', include('declarations.urls')),
    path('evaluations/', include('evaluations.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('notifications/', include('notifications.urls')),
    path('nouveautes/', include('nouveautes.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('events.urls')),
    path('', include('evenements.urls')),
    path('protected_areas/', include('protected_areas.urls')),
    re_path('validate/(?P<alias>[\w\-]+)/', validate_form, name='validate'),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('o/applications/', HttpResponseForbidden, name="creaapp"),  # surcharge d'oauth pour eviter la création d'application
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path(r'webpush/', include('webpush.urls')),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_dynamicurlpatterns(settings.STATIC_ROOT_URL)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar, CalendarAjaxView
from .views.index import HomePage
from .views.stat import Stat
from .views.stat_instructeur import StatInstructeur


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', Calendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('calendar/ajax/', CalendarAjaxView.as_view(), name="calendar_ajax"),
    path('stat/', Stat.as_view(), name="stat"),
    path('stat_instructeur/', StatInstructeur.as_view(), name="stat_instructeur"),
]

portail/forms.py
from django.forms import Form, DateField
from bootstrap_datepicker_plus import DatePickerInput


class CalendrierForm(Form):
    # Formulaire qui permet de générer un input date avec bootstrap_datepicker_plus
    date = DateField(widget=DatePickerInput(format='%d/%m/%Y', options={'locale': 'fr'}))

portail/views/calendar.py
# coding: utf-8
import json
from django.views import View
from django.db.models import Subquery
from django.views.generic import ListView
from django.shortcuts import redirect
from django.http import HttpResponse
from events.forms import *
from events.models import *
from sports.models import Activite
from evenements.models import Manif
from portail.forms import CalendrierForm


class Calendar(ListView):
    """ Calendrier des manifestations """

    # Configuration
    model = Manifestation
    template_name = 'portail/calendar.html'

    # Overrides
    def get_queryset(self):
        now = timezone.now()
        instance = Instance.objects.get_for_request(self.request)
        departement = instance.get_departement()
        activite = self.kwargs.get('activite')
        filtre_activite = Q(activite=activite) if activite else Q()
        param_dep = self.request.GET.get('dep', None)
        param_com = self.request.GET.get('com', '0')
        if param_dep and param_dep != "0":
            if not param_dep.isdecimal():
                departement = None
            else:
                departement = Departement.objects.filter(pk=param_dep)
                departement = departement.get() if departement else None
        elif param_dep is not None:
            departement = None
        resultat = Manif.objects.filter(date_debut__gt=now, prive=False, cache=False).filter(
            Q(instruction__id__isnull=False) | Q(instance_id__isnull=True)
        ).exclude(instruction__etat__in=['interdite', 'annulée']).filter(filtre_activite)
        # Afficher les manifs du département, ou toute sur le domaine master
        if departement is not None:
            resultat = resultat.filter(ville_depart__arrondissement__departement=departement)
        if param_com != '0':
            resultat = resultat.filter(ville_depart__pk=param_com)

        return resultat.order_by('date_debut')

    def get_context_data(self, **kwargs):
        now = timezone.now()
        instance = Instance.objects.get_for_request(self.request)
        departement = instance.get_departement()
        context = super(Calendar, self).get_context_data(**kwargs)
        param_dep = self.request.GET.get('dep', None)
        param_com = self.request.GET.get('com', '0')
        liste_activite = Activite.objects.filter(
            Q(manifs__instruction__id__isnull=False) | Q(manifs__instance_id__isnull=True),
            ~Q(manifs__instruction__etat__in=['interdite', 'annulée']),
            manifs__date_debut__gt=now, manifs__cache=False, manifs__prive=False)
        if param_dep and param_dep != "0":
            if not param_dep.isdecimal():
                departement = None
            else:
                departement = Departement.objects.filter(pk=self.request.GET['dep'])
                departement = departement.get() if departement else None
                if departement:
                    liste_activite = Activite.objects.filter(
                        Q(manifs__instruction__id__isnull=False) | Q(manifs__instance_id__isnull=True),
                        ~Q(manifs__instruction__etat__in=['interdite', 'annulée']),
                        manifs__date_debut__gt=now, manifs__cache=False, manifs__prive=False,
                        manifs__ville_depart__arrondissement__departement=departement)
        elif param_dep is not None:
            departement = "0"

        context['dep_actuel'] = departement
        context['com_actuel'] = int(param_com)
        context['activities'] = liste_activite.distinct('name').order_by('name')
        context['current_activite'] = int(self.kwargs.get('activite')) if self.kwargs.get('activite') else None
        context['dep'] = Departement.objects.filter(pk__in=Subquery(
            Manif.objects.filter(date_debut__gte=timezone.now()).values('ville_depart__arrondissement__departement__pk')))
        context['comm'] = Commune.objects.filter(arrondissement__departement=departement)
        context['form'] = CalendrierForm()
        return context

class CalendarAjaxView(View):
    """ Renvoyer le pk du département selectionné sur la map """

    def get(self, request):
        departement = self.request.GET.get('dep', None)
        if not departement:
            return redirect('home_page')
        else:
            param_dep = Departement.objects.filter(name__startswith=departement)
            dep_manifestation = Departement.objects.filter(
                        pk__in=Subquery(Manif.objects.filter(date_debut__gte=timezone.now()).values('ville_depart__arrondissement__departement__pk')))
            param_dep_pk = param_dep.get().pk if param_dep else ""
            # Test si le departement selectionné a des manifestations -> affiche une modale dans le template
            if dep_manifestation.filter(pk=param_dep_pk).exists():
                return HttpResponse(json.dumps({"pk": param_dep_pk}), content_type="application/json")
            else:
                return HttpResponse(json.dumps({"pk": 0}), content_type="application/json")

portail/views/index.py
# coding: utf-8
from django.views.generic.base import TemplateView
from django.shortcuts import render
from django.http import JsonResponse

from core.models.instance import Instance


class HomePage(TemplateView):
    """ Page d'accueil """

    # Configuration
    template_name = 'portail/index.html'

    # Méthodes
    def get_context_data(self, **kwargs):
        """ Définir le contexte d'affichage de la page """
        context = super(HomePage, self).get_context_data(**kwargs)
        instance = Instance.objects.get_for_request(self.request)
        context['INSTANCES'] = Instance.objects.configured()
        context['IS_MASTER'] = instance.is_master()
        # Domaine sans instance : ne pas afficher le calendrier
        context['HIDE_CALENDAR'] = instance.is_master()
        return context


def erreur400view(request, exception):
    return render(request, '400.html', {'message': exception}, status=400)


def erreur403view(request, exception):
    return render(request, '403.html', {'message': exception}, status=403)


def erreur404view(request, exception):
    path_list = request.path.split('/')
    if path_list[1] == "api":
        return JsonResponse({"detail": "Ressource non trouvée"},
                            safe=False, json_dumps_params={'ensure_ascii': False},
                            status=404)
    return render(request, '404.html', {'message': exception}, status=404)


def erreur500view(request):
    path_list = request.path.split('/')
    if path_list[1] == "api":
        return JsonResponse({"detail": "Erreur serveur"},
                            safe=False, json_dumps_params = {'ensure_ascii': False},
                            status=500)
    return render(request, '500.html', status=500)

portail/templates/portail/calendar.html
{% extends "base.html" %}

{% load static i18n %}

{% block head_title %}Calendrier{% endblock %}

{% block custom_head %}
    <link href='{% static 'portail/css/fullcalendar-custom.css' %}' rel='stylesheet'/>
    <link href='{% static 'libs/fullcalendar/css/main.css' %}' rel='stylesheet' />
    <link href='{% static 'libs/fullcalendar/css/daygrid.css' %}' rel='stylesheet'/>
    <link href='{% static 'libs/fullcalendar/css/list.css' %}' rel='stylesheet'/>
    <link href='{% static 'libs/fullcalendar/css/bootstrap.css' %}' rel='stylesheet'/>
    <link href='{% static 'libs/fullcalendar/css/timegrid.css' %}' rel='stylesheet'/>
    <script src='{% static 'libs/fullcalendar/js/main.js' %}'></script>
    <script src='{% static 'libs/fullcalendar/js/daygrid.js' %}'></script>
    <script src='{% static 'libs/fullcalendar/js/list.js' %}'></script>
    <script src='{% static 'libs/fullcalendar/js/locale-fr.js' %}'></script>
    <script src='{% static 'libs/fullcalendar/js/bootstrap.js' %}'></script>
    <script src='{% static 'libs/fullcalendar/js/timegrid.js' %}'></script>
{% endblock %}

{% block page_title %}
    {% if dep_actuel %}
        <h1>Manifestations sportives à venir dans le département {{ dep_actuel }}</h1>
    {% else %}
        <h1>Veuillez choisir votre département :</h1>
    {% endif %}
{% endblock %}

{% block content %}
    {% if dep_actuel is None %}
        <div class="container d-flex justify-content-center">
            <div id="carte-fr" style="height: 35vw; width: 35vw;" ></div>
        </div>

    {% else %}
        <div class="d-flex flex-wrap mt-0 mb-4">
            <div class="d-flex flex-column ml-auto ml-md-0" id="choix-activite">
                <label for="activite">Activité :</label>
                <select class="form-control" id="activite" name="activite">
                    <option value=""> Toutes </option>
                    {% for activite in activities %}
                        {% if activite.pk == current_activite  %}
                            <option selected value="{{ activite.pk }}">{{ activite }}</option>>
                        {% else %}
                            <option value="{{ activite.pk }}">{{ activite }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-column ml-auto"  id="choix-departement">
                <label for="departement">Département :</label>
                <select class="form-control" id="departement" name="departement">
                    {% for departement in dep %}
                        {% if departement == dep_actuel %}
                            <option value="{{ departement.pk }}" selected>{{ departement }}</option>
                        {% else %}
                            <option value="{{ departement.pk }}">{{ departement }}</option>
                        {% endif %}

                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-column ml-auto"  id="choix-commune">
                <label for="commune">Commune :</label>
                <select class="form-control" id="commune" name="commune">
                    <option value="0"> Toutes </option>
                    {% for com in comm %}
                        {% if com.pk == com_actuel %}
                            <option value="{{ com.pk }}" selected>{{ com }}</option>
                        {% else %}
                            <option value="{{ com.pk }}">{{ com }}</option>
                        {% endif %}
                    {% endfor %}
                </select>
            </div>
            <div class="d-flex flex-column ml-auto" id="choix-date">
                <label for="date">Date :</label>
                {% for field in form %}
                    {{ field }}
                {% endfor %}
                {{ form.media }}
            </div>
        </div>
        <div id='calendar'></div>
        <div class="mt-3"><small>Ce calendrier affiche toutes les manifestations sportives dont le dossier a été déposé par l'organisateur auprès du service instructeur par l'intermédiaire de cette plateforme.<br>
            Les manifestations affichées peuvent être en cours d'instruction.<br>
            Les manifestations interdites ou annulées ne sont pas affichées.
        </small></div>
    {% endif %}
{% endblock %}

{% block extra_js %}

    <script>
        let events = [];
        function getRandomColor() {
            let colors = [
                '#89949C','#495057','#015a70','#004570','#99A300','#0078B4',
                '#00355D', '#6c757d','#a0acb4','#a4874d','#33687D','#A4874D'
            ];
            return colors[Math.floor(Math.random() * 12)];
        }

        {% for manif in object_list %}
            var color = getRandomColor();
            var event = {
                title: "{{ manif.nom|safe|capfirst }}",
                departure: "{{ manif.ville_depart.name }}",
                start: "{{ manif.date_debut|date:'c' }}",
                end: "{{ manif.date_fin|date:'c' }}",
                url: "/evenement/" + {{ manif.id }} + "/",
                activite: "{{ manif.activite }}",
                dep: "{{ manif.ville_depart.get_departement.name }}",
                backgroundColor: color,
                borderColor: color,
                icone_dossier: '<i class="dossier"></i>',
                icone_depart: '<i class="ville"></i>',
                icone_activite: '<i class="activite"></i>',
                icone_instruction: '',
            {% if not request.user.is_anonymous %}
                icone_dossier: '<i class="dossier" data-titre="Pas d\'instruction pour cet événement"></i>',
                {% if manif.instruction.etat == 'autorisée' %}
                    icone_instruction: '<i class="autorisee"></i>',
                {% elif manif.instruction.etat == 'demandée' %}
                    icone_instruction: '<i class="demandee"></i>',
                {% elif manif.instruction.etat == 'distribuée' %}
                    icone_instruction: '<i class="distribuee" data-titre="Instruction en cours par les services"></i>',
                {% endif %}
            {% endif %}
            };
            events.push(event);
        {% endfor %}

        $(document).ready(function(){
            // Sources : https://fullcalendar.io/
            let calendarEl = document.getElementById('calendar');
            let calendar = new FullCalendar.Calendar(calendarEl,{
                events: events,
                plugins: [ 'dayGrid', 'bootstrap', 'timeGrid', 'list' ],
                defaultView: 'dayGridMonth',
                weekends: true,
                weekNumbers: false,
                views: {
                    dayGrid : {
                        eventLimit: 3,
                        displayEventTime: false,
                    },
                    timeGrid : {
                        minTime: "06:00:00",
                        maxTime: "20:00:00",
                        displayEventTime: true,
                        timeGridEventMinHeight: 50,
                    },
                },
                eventLimitText: 'cliquez pour voir',
                columnHeaderFormat: { weekday: 'long' },
                locale: 'fr',
                themeSystem: 'bootstrap',
                header: {
                    left: 'today prev,next',
                    center: 'title',
                    right: 'dayGridMonth,timeGridWeek,timeGridDay listMonth'
                },
                buttonText: {
                    listMonth: 'Liste mensuelle',
                },
                height: 'auto',
                titleFormat: { year: 'numeric', month: 'long', day: 'numeric' },
                eventRender: function(info) {
                    let html;
                    if (info.event.extendedProps.icone_instruction){
                        html = '<div>' + info.event.extendedProps.icone_instruction;
                    }
                    else {
                        html = '<div>' + info.event.extendedProps.icone_dossier;
                    }
                    html += info.event.title + '<br>' +
                        info.event.extendedProps.icone_depart {% if not dep_actuel or dep_actuel == "0"  %} +
                            info.event.extendedProps.dep+" "{% endif %} + info.event.extendedProps.departure {% if not current_activite %} +
                            '<br>'+info.event.extendedProps.icone_activite+info.event.extendedProps.activite{% endif %}+'</div>';
                    let eventEl = $(info.el);
                    let title;
                    if (info.view.type === 'dayGridMonth'){
                        title = eventEl.find('div.fc-content').html(html);
                    }
                    else if (info.view.type === 'timeGridWeek' || info.view.type === 'timeGridDay'){
                        title = eventEl.find('.fc-title').html(html);
                    }
                    return eventEl[0];
                },
                eventPositioned: function(){
                    AfficherIcones();
                }
            });
            calendar.render();

            $('input[name="date"]').on('dp.change', function (e) {
                let date = e.date.format("YYYY-MM-DD");
                calendar.changeView('timeGridDay', date);
            });

            $('#activite').on('change', function () {
                let pk = $('#activite').val();
                if(pk !== '') {
                    if (window.location.search){
                        window.location.assign("/calendar/" + pk + "/"+window.location.search);
                    }
                    else{
                        window.location.assign("/calendar/" + pk + "/");
                    }

                } else {
                    if (window.location.search){
                        window.location.assign("/calendar/"+window.location.search);
                    }
                    else {
                        window.location.assign("/calendar/");
                    }

                }
            });

            $('#departement').on('change', function () {
                let pk = $(this).val();
                let actual = window.location.origin+window.location.pathname;
                window.location.assign(actual+'?dep='+pk);
            });

            $('#commune').on('change', function () {
                let pk = $(this).val();
                let pk_dep = $('#departement').val();
                let actual = window.location.origin+window.location.pathname;
                if (pk != '0') {
                    window.location.assign(actual + '?dep=' + pk_dep + '&com=' + pk);
                } else {
                    window.location.assign(actual + '?dep=' + pk_dep);
                }
            });

            // Adapter la forme du select_chosen à celle du boostrap_datepicker
            $('.chosen-single').css('height', '34px').css('line-height', '34px');
            $('.chosen-single div').css('top', '5px');

        })
        try {
            map = new jvm.Map({
                container: $('#carte-fr'),
                map: 'fr_merc',
                backgroundColor: '#015a70',
                regionsSelectable: true,
                regionStyle: {

                    hover: {
                        fill: '#9aa400'
                    },
                    selected: {
                        fill: '#9aa400'
                    },
                },
                onRegionClick: function (e, code) {
                    let departement = code.substring(3)

                    console.log(departement)

                    $.get("{% url 'portail:calendar_ajax' %}?dep=" + departement, function (reponse) {
                        if (reponse['pk'] !== 0 && reponse['pk'] !== undefined) {
                            window.location.href = "{% url 'portail:calendar' %}?dep=" + reponse['pk']
                        } else {
                            var departement = map.mapData.paths[code].name;
                            $('#myModal .modal-header').text(departement);
                            $('#myModal .modal-body').html("Le calendrier ne peut être affiché car ce département ne propose pas la dématérialisation des demandes sur cette plateforme.<br>" +
                                "Nous vous invitons à vous inscrire pour nous permettre de vous tenir informé dès que la situation évolue...");
                            $('#myModal').modal();
                        }
                    })
                }
            });
            if (dep_number != "NATIONALE") {
                map.setSelectedRegions("FR-" + dep_number);
            }

        } catch (e) {

        }
    </script>
{% endblock %}