administrative_division/urls.py
# coding: utf-8
from django.urls import path

from administrative_division.views.ajax import CommuneAJAXView


app_name = 'administrative_division'
urlpatterns = [

    # Widget AJAX
    path('ajax/commune/', CommuneAJAXView.as_view(), name='commune_widget'),

]

api/urls.py
from django.urls import include, path, re_path

from api.views.carto import PoiView
from api.views.viewsets import OrganisateurViewSet, SiteN2KViewSet
from api.views.manif import ManifestationViewSet, ManifPublicViewSet, ManifEnvViewSet
from api.views.instruction import InstructionViewSet
from api.views.avis import AvisView
from rest_framework import routers, permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi


app_name = 'api'
router = routers.DefaultRouter()
router.register(r'Calendrier', ManifPublicViewSet, basename='Calendrier')
router.register(r'Organisateur', OrganisateurViewSet)
router.register(r'Instruction', InstructionViewSet, basename='Instruction')
router.register(r'Evenement', ManifestationViewSet, basename='Evenement')
router.register(r'Avis', AvisView, basename='Avis')
router.register(r'Evenement_environnement', ManifEnvViewSet, basename='Evenement_environnement')
router.register(r'SiteN2K', SiteN2KViewSet, basename='SiteN2K')
router.register(r'Pois', PoiView, basename='Pois')

schema_view = get_schema_view(
    openapi.Info(
        title="API de manifestationSportive.fr",
        default_version='v1',
        description="Permet l'utilisation de la plateforme à partir d'une autre application\n"
                    "Les urls affichées sont celles que vous pouvez accèder",
        contact=openapi.Contact(name="Openscop", url="https://www.openscop.fr/", email="contact@openscop.fr"),
        license=openapi.License(name="Creative Commons BY-NC-ND 4.0", url="https://creativecommons.org/licenses/by-nc-nd/4.0/")
    ),
    public=False,
    patterns=[path('api/', include(router.urls))],
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('', include(router.urls)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

]

configuration/urls.py
from forum.urls import urlpatterns as machina_urls

from django.conf import settings
from django.urls import include, path, re_path
from django.conf.urls.static import static
from django.http import HttpResponseBadRequest, HttpResponseForbidden

from django.contrib import admin
from django.contrib.sitemaps import views as sitemaps_views
from django.contrib.flatpages.sitemaps import FlatPageSitemap
from core.util.dynamic_static import staticfiles_dynamicurlpatterns
from core.views.user import (ProfileDetailView, UserUpdateView, signupagentview, signuporganisateurview, login,
                             EmailConfirmedView, NomPrenomChange, PasswordExpired, PasswordChangeCustomView,
                             RenvoiMailConfirm, PasswordResetCustomView, ProfilPublicView)
from core.views.instance import SendMailVerifInstance
from core.views.optionuser import ParametreNotificationMessagerie
from core.views.media import media_access
from core.views.logs_SMTP import ListLogUser, LogsDetailView, ResolutionLog
from portail.views.index import HomePage
from forum.forum_conversation.view import ForumAbonnementMultiUpdateView

admin.autodiscover()

sitemaps = {
    'flatpages': FlatPageSitemap,
}
handler400 = 'portail.views.erreur400view'
handler403 = 'portail.views.erreur403view'
handler404 = 'portail.views.erreur404view'
handler500 = 'portail.views.erreur500view'

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('sitemap\.xml', sitemaps_views.sitemap, {'sitemaps': sitemaps}),
    path('accounts/signup/', HttpResponseBadRequest),
    path('accounts/login/', login, name='account_login'),
    path('accounts/password/change/', PasswordChangeCustomView.as_view(), name='password_change_custom'),
    path('accounts/password/reset/', PasswordResetCustomView.as_view(), name='password_reset_custom'),
    path('accounts/', include('allauth.urls')),
    path('accounts/passwordexpired', PasswordExpired.as_view(), name="password_expired"),
    path('accounts/send_confirm_mail/<int:pk>/', RenvoiMailConfirm.as_view(), name="send_confirm_mail"),
    path('accounts/email_confirmed', EmailConfirmedView.as_view(), name='email_confirmed'),
    path('profile/<int:pk>/', ProfilPublicView.as_view(), name='profile_publique'),
    path('accounts/profile/', ProfileDetailView.as_view(), name='profile'),
    path('accounts/profile/edit', UserUpdateView.as_view(), name='profile_edit'),
    path('accounts/profilte/name', NomPrenomChange.as_view(), name="nom_prenom_change"),
    path('accounts/profile/notification/edit', ParametreNotificationMessagerie.as_view(), name='parametre_notification_messagerie'),
    path('accounts/profile/gerer_mes_abonnements', ForumAbonnementMultiUpdateView.as_view(), name='gerer_mes_abonnements'),
    path('inscription/agent', signupagentview, name='inscription_agent'),
    path('inscription/organisateur', signuporganisateurview, name='inscription_organisateur'),
    re_path('core/instance/(?P<pk>\d+)/', SendMailVerifInstance.as_view(), name='verif_mail_instance'),
    path('carto/', include('carto.urls')),
    path('instructions/', include('instructions.urls')),
    path('incidence/', include('evaluation_incidence.urls')),
    path('sports/', include('sports.urls')),
    path('administrative_division/', include('administrative_division.urls')),
    path('', include('evenements.urls')),
    path('ajax_select/', include('ajax_select.urls')),
    path('', include('portail.urls')),
    path('', HomePage.as_view(), name='home_page'),
    path('aide/', include('aide.urls')),
    path('api/', include('api.urls')),
    path('messagerie/', include('messagerie.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('o/applications/', HttpResponseForbidden, name="creaapp"),  # surcharge d'oauth pour eviter la création d'application
    path('o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    path(r'webpush/', include('webpush.urls')),
    path('forum/', include(machina_urls), name='forum'),
    path('list_logs/', ListLogUser.as_view(), name='list_logs'),
    path('detail_log/<int:pk>/', LogsDetailView.as_view(), name='detail_log'),
    path('detail_log/upd/<int:pk>/', ResolutionLog.as_view(), name='resolution_log'),
    path('structure/', include('structure.urls'), name='structure.urls'),
]

# ici on choisis l'url media qu'on veut utiliser en debug, les non protegés sinon les protegés
if settings.DEBUG and not settings.TESTS_IN_PROGRESS:
    import debug_toolbar
    urlpatterns = [path('__debug__/', include(debug_toolbar.urls))] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_dynamicurlpatterns(settings.STATIC_ROOT_URL)
else:
    urlpatterns += re_path(r'^media/(?P<path>.*)', media_access, name='media'),

# Les flatpages doivent être toujours après les média pour eviter une interceptions des demandes de media
urlpatterns += path('', include('django.contrib.flatpages.urls')),

evenements/urls.py
# coding: utf-8
from django.urls import path

from .views.dnm import DnmCreate, DnmDetail, DnmUpdate, DnmDelete
from .views.dcnm import DcnmCreate, DcnmDetail, DcnmUpdate, DcnmDelete
from .views.dnmc import DnmcCreate, DnmcDetail, DnmcUpdate, DnmcDelete
from .views.dcnmc import DcnmcCreate, DcnmcDetail, DcnmcUpdate, DcnmcDelete
from .views.dvtm import DvtmCreate, DvtmDetail, DvtmUpdate, DvtmDelete
from .views.avtm import AvtmCreate, AvtmDetail, AvtmUpdate, AvtmDelete
from .views.dvtmcir import DvtmcirCreate, DvtmcirDetail, DvtmcirUpdate, DvtmcirDelete
from .views.dashboard import TableauOrganisateurBody, TableauOrganisateurListe, ConsultManifListe
from .views.manif import ManifInstructeurUpdate, ManifPublicDetail, ManifUrlGen, ManifHistoriquePopup
from .views.ajax import ManifClonageAjax, ManifDepotAjax, ManifInstructeurDemandeModifAjax, GetParcoursElementView
from .views.sansinstance import SansInstanceManifCreate
from .views.create import CreationEvenementView
from .views.exportation import ExportPourInstructeur, ExportPourOrganisateur, ExportPourAgent
from .views.piecejointe import OrganisateurPieceJointeView


app_name = 'evenements'
urlpatterns = [

    # Tableau de bord principal
    path('tableau-de-bord-organisateur/', TableauOrganisateurBody.as_view(), name="tableau-de-bord-organisateur"),
    path('tableau-de-bord-organisateur/<int:pk>/', TableauOrganisateurBody.as_view(), name="tableau-de-bord-organisateur"),
    path('tableau-de-bord-organisateur/<int:pk>/liste', TableauOrganisateurListe.as_view(), name="tableau_organisateur_liste"),

    path('evenement/creation/', CreationEvenementView.as_view(), name='creation_evenement'),

    # Manifestation sans type (non supporté)
    path('sansinstance/add/', SansInstanceManifCreate.as_view(), name="manif_sansinstance_add"),

    # Modifications instructeur
    path('evenement/<int:pk>/instruction/', ManifInstructeurUpdate.as_view(), name="manifestation_instructeur"),
    path('evenement/<int:pk>/modification/', ManifInstructeurDemandeModifAjax.as_view(), name="manifestation_modification"),
    path('evenement/<int:pk>/cloner/', ManifClonageAjax.as_view(), name="manif_clone"),
    path('evenement/<int:pk>/autoriser/', ManifDepotAjax.as_view(), name="manif_depot"),
    path('evenement/<int:pk>/commune_traversee/', GetParcoursElementView.as_view(), name="commune_traversee"),

    path('evenement/<int:pk>/piecejointe/', OrganisateurPieceJointeView.as_view(), name='pj_organisateur'),

    path('evenement/<int:pk>/historique/', ManifHistoriquePopup.as_view(), name='historique_popup'),

    path('evenement/<int:pk>/export/instructeur/', ExportPourInstructeur.as_view(), name="export_manif_instructeur"),
    path('evenement/<int:pk>/export/organisateur/', ExportPourOrganisateur.as_view(), name="export_manif_organisateur"),
    path('evenement/<int:pk>/export/agent/', ExportPourAgent.as_view(), name="export_manif_agent"),

    path('evenement/<int:pk>/', ManifPublicDetail.as_view(), name="manif_detail"),
    path('manifestation/<int:pk>/', ManifUrlGen.as_view(), name="manif_url"),
    path('consultation/<int:pk>/', ConsultManifListe.as_view(), name="consultation_manif"),

    # Dnm urls
    path('Dnm/add/', DnmCreate.as_view(), name="dnm_add"),
    path('Dnm/<int:pk>/edit/', DnmUpdate.as_view(), name="dnm_update"),
    path('Dnm/<int:pk>/delete/', DnmDelete.as_view(), name="dnm_delete"),
    path('Dnm/<int:pk>/', DnmDetail.as_view(), name="dnm_detail"),

    # Dnmc urls
    path('Dnmc/add/', DnmcCreate.as_view(), name="dnmc_add"),
    path('Dnmc/<int:pk>/edit/', DnmcUpdate.as_view(), name="dnmc_update"),
    path('Dnmc/<int:pk>/delete/', DnmcDelete.as_view(), name="dnmc_delete"),
    path('Dnmc/<int:pk>/', DnmcDetail.as_view(), name="dnmc_detail"),

    # Dcnm urls
    path('Dcnm/add/', DcnmCreate.as_view(), name="dcnm_add"),
    path('Dcnm/<int:pk>/edit/', DcnmUpdate.as_view(), name="dcnm_update"),
    path('Dcnm/<int:pk>/delete/', DcnmDelete.as_view(), name="dcnm_delete"),
    path('Dcnm/<int:pk>/', DcnmDetail.as_view(), name="dcnm_detail"),

    # Dcnmc urls
    path('Dcnmc/add/', DcnmcCreate.as_view(), name="dcnmc_add"),
    path('Dcnmc/<int:pk>/edit/', DcnmcUpdate.as_view(), name="dcnmc_update"),
    path('Dcnmc/<int:pk>/delete/', DcnmcDelete.as_view(), name="dcnmc_delete"),
    path('Dcnmc/<int:pk>/', DcnmcDetail.as_view(), name="dcnmc_detail"),

    # Dvtm urls
    path('Dvtm/add/', DvtmCreate.as_view(), name="dvtm_add"),
    path('Dvtm/<int:pk>/edit/', DvtmUpdate.as_view(), name="dvtm_update"),
    path('Dvtm/<int:pk>/delete/', DvtmDelete.as_view(), name="dvtm_delete"),
    path('Dvtm/<int:pk>/', DvtmDetail.as_view(), name="dvtm_detail"),

    # Avtm urls
    path('Avtm/add/', AvtmCreate.as_view(), name="avtm_add"),
    path('Avtm/<int:pk>/edit/', AvtmUpdate.as_view(), name="avtm_update"),
    path('Avtm/<int:pk>/delete/', AvtmDelete.as_view(), name="avtm_delete"),
    path('Avtm/<int:pk>/', AvtmDetail.as_view(), name="avtm_detail"),

    # Dvtmcir urls
    path('Dvtmcir/add/', DvtmcirCreate.as_view(), name="dvtmcir_add"),
    path('Dvtmcir/<int:pk>/edit/', DvtmcirUpdate.as_view(), name="dvtmcir_update"),
    path('Dvtmcir/<int:pk>/delete/', DvtmcirDelete.as_view(), name="dvtmcir_delete"),
    path('Dvtmcir/<int:pk>/', DvtmcirDetail.as_view(), name="dvtmcir_detail"),

]

portail/urls.py
# coding: utf-8
from django.urls import path, re_path

from .views.calendar import Calendar, CalendarAjaxView
from .views.index import HomePage
from .views.stat import AbsenceInstructionMairieCount, StatBodyView, StatAsync


app_name = 'portail'
urlpatterns = [

    # Accueil
    path('', HomePage.as_view(), name='home_page'),

    # Calendrier
    re_path('calendar/(?P<activite>\d+)/', Calendar.as_view(), name="filtered_calendar"),
    path('calendar/', Calendar.as_view(), name="calendar"),
    path('calendar/ajax/', CalendarAjaxView.as_view(), name="calendar_ajax"),
    # Stat
    path('stat/', StatBodyView.as_view(), name="stat"),
    path('stat_ajax/', StatAsync.as_view(), name="stat_ajax"),
    path('compteur_absence_instruction_mairie/', AbsenceInstructionMairieCount.as_view(), name='compteur_absence_instruction_mairie'),
]

evenements/views/avtm.py
# coding: utf-8
from .manif import ManifDetail, ManifCreate, ManifUpdate, ManifDelete
from ..forms.vtm import AvtmForm
from ..models.vtm import Avtm


class AvtmDetail(ManifDetail):
    """ Détail de manifestation """

    # Confugration
    model = Avtm


class AvtmCreate(ManifCreate):
    """ Création de manifestation """

    # Configuration
    model = Avtm
    form_class = AvtmForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtm'
        return context


class AvtmUpdate(ManifUpdate):
    """ Modification de la manifestation """

    # Configuration
    model = Avtm
    form_class = AvtmForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['type'] = 'avtm'
        return context


class AvtmDelete(ManifDelete):
    """ Supprimer une manifestation """

    # Configuration
    model = Avtm

evenements/views/create.py
import json
from django.views.generic.edit import FormView
from django.utils.decorators import method_decorator
from django.shortcuts import redirect

from sports.models.sport import Discipline
from administrative_division.models.departement import Departement
from core.util.permissions import require_type_organisation
from ..forms.create import CreationEvenementForm
from ..models.manifestation import Manif
from structure.models import StructureOrganisatrice


class CreationEvenementView(FormView):
    template_name = 'evenements/recherche_creation_formulaire.html'
    form_class = CreationEvenementForm
    success_url = '/thanks/'

    # Overrides
    @method_decorator(require_type_organisation([StructureOrganisatrice,]))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        dept = Departement.objects.get(id=int(form['departement'].data))
        self.request.session['commune'] = form['ville_depart'].data
        self.request.session['discipline'] = form['discipline'].data
        self.request.session['activite'] = form['activite'].data
        self.request.session['nb_participants'] = form['nb_participants'].data
        self.request.session['emprise'] = form['emprise'].data
        self.request.session['competition'] = form['competition'].data
        self.request.session['circuit'] = form['type_circuit'].data
        if form['formulaire'].data == 'Avtm':
            if int(form['emprise'].data) in [Manif.EMPRISE['hors'], Manif.EMPRISE['partiel'], Manif.EMPRISE['temp']]:
                self.request.session['vtm_hors_circulation'] = True
        url = '/' + form['formulaire'].data + '/add/?dept=' + dept.name
        if dept not in Departement.objects.configured():
            url = '/sansinstance/add/?dept=' + dept.name
            return redirect(url)
        else:
            return redirect(url)

    def get_context_data(self, **kwargs):
        self.request.session['extradata'] = ''
        context = super().get_context_data(**kwargs)
        context['ancien_manifs'] = Manif.objects.filter(structure_organisatrice_fk__in=self.request.user.organisation_m2m.all())
        context['vtm'] = list(Discipline.objects.motorise().values_list('id', flat=True))
        context['emprise'] = json.dumps(Manif.EMPRISE)
        context['circuit'] = json.dumps(Manif.CIRCUIT)
        return context

evenements/templates/evenements/avis_pdf.html
{% load static i18n file_tags %}


<meta http-equiv="content-type" content="text/html; charset=utf-8">
<div class="head"><img src="{% static 'portail/img/Logo_vert.png' %}"/></div>

<h1>Manifestation : {{ manif }}</h1>




<div>
    <h2>Avis</h2>
    {% for avis in liste_avis %}
        <h3>{{ avis|capfirst }}</h3>
        <ul class="list-group">
            <li class="list-group-item">Date de demande de l'avis : {{ avis.date_demande }}</li>
            {% if avis.etat == 'rendu' %}
                <li class="list-group-item">Date de rendu de l'avis : {{ avis.date_reponse|default_if_none:"Pas encore rendu" }}</li>
            {% endif %}
            {% if avis.etat == 'rendu' %}
                <li class="list-group-item">Favorable : {{ avis.favorable|yesno|title }}</li>
                <li class="list-group-item">Contenu de l'avis: {{ avis.prescriptions|linebreaks }}</li>
            {% endif %}
            {% if avis.docs.all %}
                <div class="mt-2 mb-2">Pièces jointes :</div>
                {% for doc in avis.docs.all %}
                    <li class="list-group-item"> <a href="{{ doc.fichier.url }}" target="_blank">{{ doc.fichier|basename }}</a></li>
                {% endfor %}
            {% endif %}
        </ul>
    {% endfor %}
</div>



<style>
    @page  {
        size: A4;
        margin: 1cm;
    }
    .head{
        padding: 0.3cm;
    }
    .list-group-item{
        margin: 0.4em;
    }
    .card-header{
      font-weight: bold;

    }


</style>

evenements/templates/evenements/erreur_exportation.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}Erreur de l'exportation en pdf{% endblock %}
{% block page_title %}
    <h1>Erreur de l'exportation en pdf</h1>
{% endblock %}

{% block content %}
    <p>{{ message|safe }}</p>
    <p><a href="{% url "home_page" %}" class="btn btn-primary" role="button">Retour à la page d'accueil</a></p>
{% endblock %}

evenements/templates/evenements/evenement_clone_form.html
{% load crispy_forms_tags i18n static %}

<link href="{% static 'libs/bootstrap-datetimepicker/css/bootstrap-datetimepicker.css' %}" type="text/css" media="all" rel="stylesheet">
<link href="/static/bootstrap_datepicker_plus/css/datepicker-widget.css" type="text/css" media="all" rel="stylesheet">

<script type="text/javascript" src="{% static 'libs/moment/moment-with-locales.min.js' %}"></script>
<script type="text/javascript" src="{% static 'libs/bootstrap-datetimepicker/js/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="/static/bootstrap_datepicker_plus/js/datepicker-widget.js"></script>

{% block head_title %}{% endblock %}

{% block content %}

    {% if form.errors %}
        <div class="alert alert-danger">
            <ul>
                {% if form.non_field_errors %}
                    <li>{{ form.non_field_errors }}</li>
                {% endif %}
                {% for field in form %}
                    {% if field.errors %}
                        <li><strong>{{ field.label }}</strong> : {{ field.errors.0 }}</li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
    {% endif %}

    {% block form %}
        <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" id="clone-form">
            {{ form.media }}
            {% crispy form %}
        </form>
    {% endblock %}

{% endblock %}

evenements/templates/evenements/evenement_form.html
{% extends "base_form.html" %}

{% load crispy_forms_tags %}
{% load i18n verbose_tags %}
{% load static %}

{% block head_title %}
    Organisation d'une manifestation sportive
{% endblock %}

{% block page_title %}
    {% if object.manifestation_ptr %}
        {% include 'evenements/pictos/type_evenement.html' with manif=object.manifestation_ptr%}
    {% else %}
        {% include 'evenements/pictos/type_evenement.html' with manif=object%}
    {% endif %}
    &nbsp;
    {% if form.target and form.target.pk %}
        {{ object.manifestation_ptr.get_cerfa|verbose_name|capfirst }}<br>
        Nom de la manifestation : <strong>{{ form.target }}</strong>
    {% else %}
        &nbsp;{{ verbose|capfirst }}
    {% endif %}
{% endblock %}

{% block form %}
    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data" id="manifestation-form">
        {% if form.target.id %}<input type="hidden" name="id" id="id_id" value="{{ form.target.id }}">{% endif %}
        {% crispy form %}
        {{ form.media }}
        <div class="form-actions">
            <input id="submit-id-save" class="btn btn-primary" type="submit" value="Enregistrer" name="save">
            {% if form.instance.id %}
                <a class="btn btn-danger" href="javascript:history.back()">Annuler</a>
            {% endif %}

        </div>
    </form>
{% endblock %}

{% block extra_js %}
    <script>
        const url_liste_commune = "{% url 'administrative_division:commune_widget' %}";
        {% if object.pk  %}
        const url_get_donnee_parcours = "{% url 'evenements:commune_traversee' pk=object.pk %}";
        {% else %}
        const url_get_donnee_parcours = false
        {% endif %}
        const liste_champ_modif = '{{ champ|safe }}';
        const en_instruction = {% if object.get_instruction %} true {% else %} false {% endif %};
        const type = "{{ type }}"
    </script>
    <script src='{% static "portail/js/file-validator.js" %}' type="text/javascript"></script>
    <script src='{% static "libs/autogrow/jquery.ns-autogrow.min.js" %}' type="text/javascript"></script>
    <script src='{% static "evenements/js/manifestation_formulaire.js" %}' type="text/javascript"></script>
{% endblock %}

evenements/templates/evenements/evenement_suppression.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block head_title %}
    Suppression d'une manifestation
{% endblock %}

{% block page_title %}
    <h1>Suppression d'une manifestation</h1>
{% endblock %}

{% block content %}
    <form method="post">{% csrf_token %}
        <p>Veuillez confirmer la suppression de la manifestation : <br>
            <strong><em>{{ object.nom }}</em></strong> prévue pour le {{ object.date_debut }} <br>
            Tous les pièces jointes seront également supprimés. Cette action est <u>irréversible</u> !
        </p>
        <input class="btn btn-primary" type="submit" value="Je confirme la suppression">
    </form>
{% endblock %}

evenements/templates/evenements/evenementpublic_detail.html
{% extends "base.html" %}


{% load i18n %}

{% block head_title %}{{ object|capfirst }}{% endblock %}
{% block page_title %}
    <h1>{{ object|capfirst }}</h1>
{% endblock %}

{% block content %}
    {% if request.organisation == object.structure_organisatrice_fk %}
        <div class="alert alert-warning">Cette manifestation se déroule dans un département qui n'est pas abonné à cette plateforme.<br>
            <strong>Le dossier n'a pas été transmis au service instructeur.</strong><br>
            N'hésitez pas à prendre contact avec le service d'instruction de votre département pour suivre leur consignes.
        </div>
    {% endif %}
    <div class="row">
        <div class="col-sm-6">
            <div class="card ">
                {% if not object.visible_dans_calendrier %}
                    <div class="card-body"><span class="text-danger">La manifestation a été masquée du calendrier public par l'{{ object.prive | yesno:"organisateur,instructeur" }}</span></div>
                {% endif %}
                <div class="card-body">{{ object.description|linebreaks }}</div>
                <ul class="list-group">
                    <li class="list-group-item"><strong><i class="date"></i>Début : </strong>{{ object.date_debut|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="date"></i>Fin : </strong>{{ object.date_fin|date:"d F Y - H:i" }}</li>
                    <li class="list-group-item"><strong><i class="activite"></i> Sport : </strong>{{ object.activite.discipline }} - {{ object.activite }}</li>
                    <li class="list-group-item"><strong><i class="voie-publique"></i> Sur voie publique ou ouverte à la circulation publique : </strong>
                        {% if object.emprise == 0 %}
                            Non renseignée
                        {% else %}
                            {{ object.get_emprise_display }}
                        {% endif %}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Commune de départ : </strong>{{ object.ville_depart|capfirst }}</li>
                    <li class="list-group-item"><strong><i class="lieu"></i> Communes traversées : </strong>
                        {% for ville in object.get_villes_traversees %}
                            {% if forloop.last %}
                                {{ ville }}.
                            {% else %}
                                {{ ville }},
                            {% endif %}
                        {% endfor %}
                    </li>
                </ul>
            {% if object.afficher_adresse_structure %}
                <div class="card-body">
                    <strong>Informations de contact :</strong><br>
                    {% with object.structure_organisatrice_fk as structure %}
                        {{ structure.precision_nom_s }}<br>
                        {{ structure.adresse_s }}<br>
                        <span id="ctx-help-insee-code">{{ structure.commune_m2m.first.zip_code }}</span> {{ structure.commune_m2m.first }}<br>
                        {% if structure.website %}<strong>Site web :</strong> {{ structure.site_web_s|urlize }}<br>{% endif %}
                        <strong>Téléphone :</strong> {{ structure.telephone_s }}<br>
                    {% endwith %}

                </div>
            {% endif %}
            </div>
        </div>
    </div>
    {% if object.get_type_manif %}
        <a href="{% url 'portail:calendar' %}" class="btn btn-primary">
            <i class="date"></i> Retour au calendrier des manifestations sportives</a>
    {% else %}
        <a href="{% url 'evenements:tableau-de-bord-organisateur'  pk=object.structure_organisatrice_fk.pk %}" class="btn btn-primary">
            <i class="tableau-de-bord"></i> Retour au tableau de bord</a>
    {% endif %}
{% endblock %}